/*
 * Service API
 * This API exposes endpoints.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zipper.delivery.hub.sdk.model.AddressPlaceDTO;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zipper.delivery.hub.sdk.ApiClient;
/**
 * Structured address information
 */
@JsonPropertyOrder({
  AddressDTO.JSON_PROPERTY_FULL_ADDRESS,
  AddressDTO.JSON_PROPERTY_CITY,
  AddressDTO.JSON_PROPERTY_HOUSE,
  AddressDTO.JSON_PROPERTY_STATE,
  AddressDTO.JSON_PROPERTY_STREET,
  AddressDTO.JSON_PROPERTY_COUNTRY,
  AddressDTO.JSON_PROPERTY_POSTCODE,
  AddressDTO.JSON_PROPERTY_ADDRESS_PLACE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class AddressDTO {
  public static final String JSON_PROPERTY_FULL_ADDRESS = "fullAddress";
  @jakarta.annotation.Nonnull
  private String fullAddress;

  public static final String JSON_PROPERTY_CITY = "city";
  @jakarta.annotation.Nullable
  private String city;

  public static final String JSON_PROPERTY_HOUSE = "house";
  @jakarta.annotation.Nullable
  private String house;

  public static final String JSON_PROPERTY_STATE = "state";
  @jakarta.annotation.Nullable
  private String state;

  public static final String JSON_PROPERTY_STREET = "street";
  @jakarta.annotation.Nullable
  private String street;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  @jakarta.annotation.Nullable
  private String country;

  public static final String JSON_PROPERTY_POSTCODE = "postcode";
  @jakarta.annotation.Nullable
  private String postcode;

  public static final String JSON_PROPERTY_ADDRESS_PLACE = "addressPlace";
  @jakarta.annotation.Nullable
  private AddressPlaceDTO addressPlace;

  public AddressDTO() { 
  }

  public AddressDTO fullAddress(@jakarta.annotation.Nonnull String fullAddress) {
    this.fullAddress = fullAddress;
    return this;
  }

  /**
   * Full formatted address string
   * @return fullAddress
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FULL_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFullAddress() {
    return fullAddress;
  }


  @JsonProperty(JSON_PROPERTY_FULL_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFullAddress(@jakarta.annotation.Nonnull String fullAddress) {
    this.fullAddress = fullAddress;
  }


  public AddressDTO city(@jakarta.annotation.Nullable String city) {
    this.city = city;
    return this;
  }

  /**
   * City name
   * @return city
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCity() {
    return city;
  }


  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCity(@jakarta.annotation.Nullable String city) {
    this.city = city;
  }


  public AddressDTO house(@jakarta.annotation.Nullable String house) {
    this.house = house;
    return this;
  }

  /**
   * House/building number
   * @return house
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HOUSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHouse() {
    return house;
  }


  @JsonProperty(JSON_PROPERTY_HOUSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHouse(@jakarta.annotation.Nullable String house) {
    this.house = house;
  }


  public AddressDTO state(@jakarta.annotation.Nullable String state) {
    this.state = state;
    return this;
  }

  /**
   * State or region
   * @return state
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(@jakarta.annotation.Nullable String state) {
    this.state = state;
  }


  public AddressDTO street(@jakarta.annotation.Nullable String street) {
    this.street = street;
    return this;
  }

  /**
   * Street name
   * @return street
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STREET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStreet() {
    return street;
  }


  @JsonProperty(JSON_PROPERTY_STREET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStreet(@jakarta.annotation.Nullable String street) {
    this.street = street;
  }


  public AddressDTO country(@jakarta.annotation.Nullable String country) {
    this.country = country;
    return this;
  }

  /**
   * Country code (ISO 3166-1 alpha-2)
   * @return country
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCountry() {
    return country;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(@jakarta.annotation.Nullable String country) {
    this.country = country;
  }


  public AddressDTO postcode(@jakarta.annotation.Nullable String postcode) {
    this.postcode = postcode;
    return this;
  }

  /**
   * Postal code
   * @return postcode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POSTCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPostcode() {
    return postcode;
  }


  @JsonProperty(JSON_PROPERTY_POSTCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPostcode(@jakarta.annotation.Nullable String postcode) {
    this.postcode = postcode;
  }


  public AddressDTO addressPlace(@jakarta.annotation.Nullable AddressPlaceDTO addressPlace) {
    this.addressPlace = addressPlace;
    return this;
  }

  /**
   * Third-party address place reference
   * @return addressPlace
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESS_PLACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public AddressPlaceDTO getAddressPlace() {
    return addressPlace;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS_PLACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddressPlace(@jakarta.annotation.Nullable AddressPlaceDTO addressPlace) {
    this.addressPlace = addressPlace;
  }


  /**
   * Return true if this AddressDTO object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddressDTO addressDTO = (AddressDTO) o;
    return Objects.equals(this.fullAddress, addressDTO.fullAddress) &&
        Objects.equals(this.city, addressDTO.city) &&
        Objects.equals(this.house, addressDTO.house) &&
        Objects.equals(this.state, addressDTO.state) &&
        Objects.equals(this.street, addressDTO.street) &&
        Objects.equals(this.country, addressDTO.country) &&
        Objects.equals(this.postcode, addressDTO.postcode) &&
        Objects.equals(this.addressPlace, addressDTO.addressPlace);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fullAddress, city, house, state, street, country, postcode, addressPlace);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddressDTO {\n");
    sb.append("    fullAddress: ").append(toIndentedString(fullAddress)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    house: ").append(toIndentedString(house)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    postcode: ").append(toIndentedString(postcode)).append("\n");
    sb.append("    addressPlace: ").append(toIndentedString(addressPlace)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `fullAddress` to the URL query string
    if (getFullAddress() != null) {
      joiner.add(String.format("%sfullAddress%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFullAddress()))));
    }

    // add `city` to the URL query string
    if (getCity() != null) {
      joiner.add(String.format("%scity%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCity()))));
    }

    // add `house` to the URL query string
    if (getHouse() != null) {
      joiner.add(String.format("%shouse%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHouse()))));
    }

    // add `state` to the URL query string
    if (getState() != null) {
      joiner.add(String.format("%sstate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getState()))));
    }

    // add `street` to the URL query string
    if (getStreet() != null) {
      joiner.add(String.format("%sstreet%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStreet()))));
    }

    // add `country` to the URL query string
    if (getCountry() != null) {
      joiner.add(String.format("%scountry%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCountry()))));
    }

    // add `postcode` to the URL query string
    if (getPostcode() != null) {
      joiner.add(String.format("%spostcode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPostcode()))));
    }

    // add `addressPlace` to the URL query string
    if (getAddressPlace() != null) {
      joiner.add(getAddressPlace().toUrlQueryString(prefix + "addressPlace" + suffix));
    }

    return joiner.toString();
  }
}

