/*
 * Service API
 * This API exposes endpoints.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zipper.delivery.hub.sdk.model.ExponentialRetryBackoffDTO;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zipper.delivery.hub.sdk.ApiClient;
/**
 * Callback delivery configuration
 */
@JsonPropertyOrder({
  CallbackConfigDTO.JSON_PROPERTY_EXPONENTIAL_RETRY_BACKOFF
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class CallbackConfigDTO {
  public static final String JSON_PROPERTY_EXPONENTIAL_RETRY_BACKOFF = "exponentialRetryBackoff";
  @jakarta.annotation.Nullable
  private ExponentialRetryBackoffDTO exponentialRetryBackoff;

  public CallbackConfigDTO() { 
  }

  public CallbackConfigDTO exponentialRetryBackoff(@jakarta.annotation.Nullable ExponentialRetryBackoffDTO exponentialRetryBackoff) {
    this.exponentialRetryBackoff = exponentialRetryBackoff;
    return this;
  }

  /**
   * Exponential backoff retry settings
   * @return exponentialRetryBackoff
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPONENTIAL_RETRY_BACKOFF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ExponentialRetryBackoffDTO getExponentialRetryBackoff() {
    return exponentialRetryBackoff;
  }


  @JsonProperty(JSON_PROPERTY_EXPONENTIAL_RETRY_BACKOFF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExponentialRetryBackoff(@jakarta.annotation.Nullable ExponentialRetryBackoffDTO exponentialRetryBackoff) {
    this.exponentialRetryBackoff = exponentialRetryBackoff;
  }


  /**
   * Return true if this CallbackConfigDTO object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CallbackConfigDTO callbackConfigDTO = (CallbackConfigDTO) o;
    return Objects.equals(this.exponentialRetryBackoff, callbackConfigDTO.exponentialRetryBackoff);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exponentialRetryBackoff);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CallbackConfigDTO {\n");
    sb.append("    exponentialRetryBackoff: ").append(toIndentedString(exponentialRetryBackoff)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `exponentialRetryBackoff` to the URL query string
    if (getExponentialRetryBackoff() != null) {
      joiner.add(getExponentialRetryBackoff().toUrlQueryString(prefix + "exponentialRetryBackoff" + suffix));
    }

    return joiner.toString();
  }
}

