/*
 * Service API
 * This API exposes endpoints.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zipper.delivery.hub.sdk.model.CallbackConfigDTO;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zipper.delivery.hub.sdk.ApiClient;
/**
 * Request to create or update a webhook subscription
 */
@JsonPropertyOrder({
  CreateWebhookRequest.JSON_PROPERTY_CALLBACK_URL,
  CreateWebhookRequest.JSON_PROPERTY_ENABLED,
  CreateWebhookRequest.JSON_PROPERTY_EVENT_TYPES,
  CreateWebhookRequest.JSON_PROPERTY_CALLBACK_CONFIG,
  CreateWebhookRequest.JSON_PROPERTY_WEBHOOK_SECRET
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class CreateWebhookRequest {
  public static final String JSON_PROPERTY_CALLBACK_URL = "callbackUrl";
  @jakarta.annotation.Nonnull
  private String callbackUrl;

  public static final String JSON_PROPERTY_ENABLED = "enabled";
  @jakarta.annotation.Nullable
  private Boolean enabled;

  public static final String JSON_PROPERTY_EVENT_TYPES = "eventTypes";
  @jakarta.annotation.Nonnull
  private List<String> eventTypes = new ArrayList<>();

  public static final String JSON_PROPERTY_CALLBACK_CONFIG = "callbackConfig";
  @jakarta.annotation.Nullable
  private CallbackConfigDTO callbackConfig;

  public static final String JSON_PROPERTY_WEBHOOK_SECRET = "webhookSecret";
  @jakarta.annotation.Nullable
  private String webhookSecret;

  public CreateWebhookRequest() { 
  }

  public CreateWebhookRequest callbackUrl(@jakarta.annotation.Nonnull String callbackUrl) {
    this.callbackUrl = callbackUrl;
    return this;
  }

  /**
   * HTTPS URL that will receive webhook events
   * @return callbackUrl
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CALLBACK_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCallbackUrl() {
    return callbackUrl;
  }


  @JsonProperty(JSON_PROPERTY_CALLBACK_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCallbackUrl(@jakarta.annotation.Nonnull String callbackUrl) {
    this.callbackUrl = callbackUrl;
  }


  public CreateWebhookRequest enabled(@jakarta.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * Whether the webhook is active
   * @return enabled
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getEnabled() {
    return enabled;
  }


  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnabled(@jakarta.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
  }


  public CreateWebhookRequest eventTypes(@jakarta.annotation.Nonnull List<String> eventTypes) {
    this.eventTypes = eventTypes;
    return this;
  }

  public CreateWebhookRequest addEventTypesItem(String eventTypesItem) {
    if (this.eventTypes == null) {
      this.eventTypes = new ArrayList<>();
    }
    this.eventTypes.add(eventTypesItem);
    return this;
  }

  /**
   * Event types to subscribe to
   * @return eventTypes
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EVENT_TYPES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getEventTypes() {
    return eventTypes;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_TYPES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEventTypes(@jakarta.annotation.Nonnull List<String> eventTypes) {
    this.eventTypes = eventTypes;
  }


  public CreateWebhookRequest callbackConfig(@jakarta.annotation.Nullable CallbackConfigDTO callbackConfig) {
    this.callbackConfig = callbackConfig;
    return this;
  }

  /**
   * Optional callback configuration (retry policy)
   * @return callbackConfig
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CALLBACK_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CallbackConfigDTO getCallbackConfig() {
    return callbackConfig;
  }


  @JsonProperty(JSON_PROPERTY_CALLBACK_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCallbackConfig(@jakarta.annotation.Nullable CallbackConfigDTO callbackConfig) {
    this.callbackConfig = callbackConfig;
  }


  public CreateWebhookRequest webhookSecret(@jakarta.annotation.Nullable String webhookSecret) {
    this.webhookSecret = webhookSecret;
    return this;
  }

  /**
   * Optional webhook secret. If not provided, one will be auto-generated.
   * @return webhookSecret
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WEBHOOK_SECRET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getWebhookSecret() {
    return webhookSecret;
  }


  @JsonProperty(JSON_PROPERTY_WEBHOOK_SECRET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWebhookSecret(@jakarta.annotation.Nullable String webhookSecret) {
    this.webhookSecret = webhookSecret;
  }


  /**
   * Return true if this CreateWebhookRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateWebhookRequest createWebhookRequest = (CreateWebhookRequest) o;
    return Objects.equals(this.callbackUrl, createWebhookRequest.callbackUrl) &&
        Objects.equals(this.enabled, createWebhookRequest.enabled) &&
        Objects.equals(this.eventTypes, createWebhookRequest.eventTypes) &&
        Objects.equals(this.callbackConfig, createWebhookRequest.callbackConfig) &&
        Objects.equals(this.webhookSecret, createWebhookRequest.webhookSecret);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callbackUrl, enabled, eventTypes, callbackConfig, webhookSecret);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateWebhookRequest {\n");
    sb.append("    callbackUrl: ").append(toIndentedString(callbackUrl)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    eventTypes: ").append(toIndentedString(eventTypes)).append("\n");
    sb.append("    callbackConfig: ").append(toIndentedString(callbackConfig)).append("\n");
    sb.append("    webhookSecret: ").append(toIndentedString(webhookSecret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `callbackUrl` to the URL query string
    if (getCallbackUrl() != null) {
      joiner.add(String.format("%scallbackUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCallbackUrl()))));
    }

    // add `enabled` to the URL query string
    if (getEnabled() != null) {
      joiner.add(String.format("%senabled%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEnabled()))));
    }

    // add `eventTypes` to the URL query string
    if (getEventTypes() != null) {
      for (int i = 0; i < getEventTypes().size(); i++) {
        joiner.add(String.format("%seventTypes%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getEventTypes().get(i)))));
      }
    }

    // add `callbackConfig` to the URL query string
    if (getCallbackConfig() != null) {
      joiner.add(getCallbackConfig().toUrlQueryString(prefix + "callbackConfig" + suffix));
    }

    // add `webhookSecret` to the URL query string
    if (getWebhookSecret() != null) {
      joiner.add(String.format("%swebhookSecret%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWebhookSecret()))));
    }

    return joiner.toString();
  }
}

