/*
 * Service API
 * This API exposes endpoints.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zipper.delivery.hub.sdk.ApiClient;
/**
 * Exponential backoff retry configuration
 */
@JsonPropertyOrder({
  ExponentialRetryBackoffDTO.JSON_PROPERTY_EXPONENT_BASE,
  ExponentialRetryBackoffDTO.JSON_PROPERTY_MAX_RETRY_COUNT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class ExponentialRetryBackoffDTO {
  public static final String JSON_PROPERTY_EXPONENT_BASE = "exponentBase";
  @jakarta.annotation.Nullable
  private Integer exponentBase;

  public static final String JSON_PROPERTY_MAX_RETRY_COUNT = "maxRetryCount";
  @jakarta.annotation.Nullable
  private Integer maxRetryCount;

  public ExponentialRetryBackoffDTO() { 
  }

  public ExponentialRetryBackoffDTO exponentBase(@jakarta.annotation.Nullable Integer exponentBase) {
    this.exponentBase = exponentBase;
    return this;
  }

  /**
   * Base for the exponential delay calculation (delay &#x3D; base^attempt seconds)
   * @return exponentBase
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPONENT_BASE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getExponentBase() {
    return exponentBase;
  }


  @JsonProperty(JSON_PROPERTY_EXPONENT_BASE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExponentBase(@jakarta.annotation.Nullable Integer exponentBase) {
    this.exponentBase = exponentBase;
  }


  public ExponentialRetryBackoffDTO maxRetryCount(@jakarta.annotation.Nullable Integer maxRetryCount) {
    this.maxRetryCount = maxRetryCount;
    return this;
  }

  /**
   * Maximum number of retry attempts
   * @return maxRetryCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAX_RETRY_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getMaxRetryCount() {
    return maxRetryCount;
  }


  @JsonProperty(JSON_PROPERTY_MAX_RETRY_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxRetryCount(@jakarta.annotation.Nullable Integer maxRetryCount) {
    this.maxRetryCount = maxRetryCount;
  }


  /**
   * Return true if this ExponentialRetryBackoffDTO object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExponentialRetryBackoffDTO exponentialRetryBackoffDTO = (ExponentialRetryBackoffDTO) o;
    return Objects.equals(this.exponentBase, exponentialRetryBackoffDTO.exponentBase) &&
        Objects.equals(this.maxRetryCount, exponentialRetryBackoffDTO.maxRetryCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exponentBase, maxRetryCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExponentialRetryBackoffDTO {\n");
    sb.append("    exponentBase: ").append(toIndentedString(exponentBase)).append("\n");
    sb.append("    maxRetryCount: ").append(toIndentedString(maxRetryCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `exponentBase` to the URL query string
    if (getExponentBase() != null) {
      joiner.add(String.format("%sexponentBase%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExponentBase()))));
    }

    // add `maxRetryCount` to the URL query string
    if (getMaxRetryCount() != null) {
      joiner.add(String.format("%smaxRetryCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMaxRetryCount()))));
    }

    return joiner.toString();
  }
}

