/*
 * Service API
 * This API exposes endpoints.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zipper.delivery.hub.sdk.ApiClient;
/**
 * PIN handshake configuration for a delivery
 */
@JsonPropertyOrder({
  HandshakeDeliveryDTO.JSON_PROPERTY_IS_REQUIRED,
  HandshakeDeliveryDTO.JSON_PROPERTY_SEND_SMS_TO_DROPOFF_CONTACT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class HandshakeDeliveryDTO {
  public static final String JSON_PROPERTY_IS_REQUIRED = "isRequired";
  @jakarta.annotation.Nullable
  private Boolean isRequired = false;

  public static final String JSON_PROPERTY_SEND_SMS_TO_DROPOFF_CONTACT = "sendSmsToDropoffContact";
  @jakarta.annotation.Nullable
  private Boolean sendSmsToDropoffContact = true;

  public HandshakeDeliveryDTO() { 
  }

  public HandshakeDeliveryDTO isRequired(@jakarta.annotation.Nullable Boolean isRequired) {
    this.isRequired = isRequired;
    return this;
  }

  /**
   * Enable PIN verification feature on the delivery.
   * @return isRequired
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsRequired() {
    return isRequired;
  }


  @JsonProperty(JSON_PROPERTY_IS_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsRequired(@jakarta.annotation.Nullable Boolean isRequired) {
    this.isRequired = isRequired;
  }


  public HandshakeDeliveryDTO sendSmsToDropoffContact(@jakarta.annotation.Nullable Boolean sendSmsToDropoffContact) {
    this.sendSmsToDropoffContact = sendSmsToDropoffContact;
    return this;
  }

  /**
   * When enabled, DHS will send a pre-defined SMS to recipient including the delivery PIN code. Disable only if PIN is communicated some other way.
   * @return sendSmsToDropoffContact
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEND_SMS_TO_DROPOFF_CONTACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getSendSmsToDropoffContact() {
    return sendSmsToDropoffContact;
  }


  @JsonProperty(JSON_PROPERTY_SEND_SMS_TO_DROPOFF_CONTACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSendSmsToDropoffContact(@jakarta.annotation.Nullable Boolean sendSmsToDropoffContact) {
    this.sendSmsToDropoffContact = sendSmsToDropoffContact;
  }


  /**
   * Return true if this HandshakeDeliveryDTO object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HandshakeDeliveryDTO handshakeDeliveryDTO = (HandshakeDeliveryDTO) o;
    return Objects.equals(this.isRequired, handshakeDeliveryDTO.isRequired) &&
        Objects.equals(this.sendSmsToDropoffContact, handshakeDeliveryDTO.sendSmsToDropoffContact);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isRequired, sendSmsToDropoffContact);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HandshakeDeliveryDTO {\n");
    sb.append("    isRequired: ").append(toIndentedString(isRequired)).append("\n");
    sb.append("    sendSmsToDropoffContact: ").append(toIndentedString(sendSmsToDropoffContact)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `isRequired` to the URL query string
    if (getIsRequired() != null) {
      joiner.add(String.format("%sisRequired%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsRequired()))));
    }

    // add `sendSmsToDropoffContact` to the URL query string
    if (getSendSmsToDropoffContact() != null) {
      joiner.add(String.format("%ssendSmsToDropoffContact%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSendSmsToDropoffContact()))));
    }

    return joiner.toString();
  }
}

