/*
 * Service API
 * This API exposes endpoints.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zipper.delivery.hub.sdk.ApiClient;
/**
 * Response after successfully creating a delivery
 */
@JsonPropertyOrder({
  HubCreateDeliveryResponse.JSON_PROPERTY_DELIVERY_ID,
  HubCreateDeliveryResponse.JSON_PROPERTY_DELIVERY_TYPE,
  HubCreateDeliveryResponse.JSON_PROPERTY_STATUS,
  HubCreateDeliveryResponse.JSON_PROPERTY_HUB_TRACKING_NUMBER,
  HubCreateDeliveryResponse.JSON_PROPERTY_TRACKING_URL
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class HubCreateDeliveryResponse {
  public static final String JSON_PROPERTY_DELIVERY_ID = "deliveryId";
  @jakarta.annotation.Nullable
  private UUID deliveryId;

  /**
   * Type of delivery
   */
  public enum DeliveryTypeEnum {
    STORE_IMMEDIATE(String.valueOf("STORE_IMMEDIATE")),
    
    FOOD_IMMEDIATE(String.valueOf("FOOD_IMMEDIATE")),
    
    STORE_NEXT_DAY(String.valueOf("STORE_NEXT_DAY"));

    private String value;

    DeliveryTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DeliveryTypeEnum fromValue(String value) {
      for (DeliveryTypeEnum b : DeliveryTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DELIVERY_TYPE = "deliveryType";
  @jakarta.annotation.Nullable
  private DeliveryTypeEnum deliveryType;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_HUB_TRACKING_NUMBER = "hubTrackingNumber";
  @jakarta.annotation.Nullable
  private String hubTrackingNumber;

  public static final String JSON_PROPERTY_TRACKING_URL = "trackingUrl";
  @jakarta.annotation.Nullable
  private String trackingUrl;

  public HubCreateDeliveryResponse() { 
  }

  public HubCreateDeliveryResponse deliveryId(@jakarta.annotation.Nullable UUID deliveryId) {
    this.deliveryId = deliveryId;
    return this;
  }

  /**
   * Unique delivery identifier
   * @return deliveryId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELIVERY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getDeliveryId() {
    return deliveryId;
  }


  @JsonProperty(JSON_PROPERTY_DELIVERY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeliveryId(@jakarta.annotation.Nullable UUID deliveryId) {
    this.deliveryId = deliveryId;
  }


  public HubCreateDeliveryResponse deliveryType(@jakarta.annotation.Nullable DeliveryTypeEnum deliveryType) {
    this.deliveryType = deliveryType;
    return this;
  }

  /**
   * Type of delivery
   * @return deliveryType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELIVERY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public DeliveryTypeEnum getDeliveryType() {
    return deliveryType;
  }


  @JsonProperty(JSON_PROPERTY_DELIVERY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeliveryType(@jakarta.annotation.Nullable DeliveryTypeEnum deliveryType) {
    this.deliveryType = deliveryType;
  }


  public HubCreateDeliveryResponse status(@jakarta.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Current delivery status
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable String status) {
    this.status = status;
  }


  public HubCreateDeliveryResponse hubTrackingNumber(@jakarta.annotation.Nullable String hubTrackingNumber) {
    this.hubTrackingNumber = hubTrackingNumber;
    return this;
  }

  /**
   * Hub-assigned tracking number
   * @return hubTrackingNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HUB_TRACKING_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHubTrackingNumber() {
    return hubTrackingNumber;
  }


  @JsonProperty(JSON_PROPERTY_HUB_TRACKING_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHubTrackingNumber(@jakarta.annotation.Nullable String hubTrackingNumber) {
    this.hubTrackingNumber = hubTrackingNumber;
  }


  public HubCreateDeliveryResponse trackingUrl(@jakarta.annotation.Nullable String trackingUrl) {
    this.trackingUrl = trackingUrl;
    return this;
  }

  /**
   * Public tracking URL for the delivery
   * @return trackingUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRACKING_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTrackingUrl() {
    return trackingUrl;
  }


  @JsonProperty(JSON_PROPERTY_TRACKING_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackingUrl(@jakarta.annotation.Nullable String trackingUrl) {
    this.trackingUrl = trackingUrl;
  }


  /**
   * Return true if this HubCreateDeliveryResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HubCreateDeliveryResponse hubCreateDeliveryResponse = (HubCreateDeliveryResponse) o;
    return Objects.equals(this.deliveryId, hubCreateDeliveryResponse.deliveryId) &&
        Objects.equals(this.deliveryType, hubCreateDeliveryResponse.deliveryType) &&
        Objects.equals(this.status, hubCreateDeliveryResponse.status) &&
        Objects.equals(this.hubTrackingNumber, hubCreateDeliveryResponse.hubTrackingNumber) &&
        Objects.equals(this.trackingUrl, hubCreateDeliveryResponse.trackingUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deliveryId, deliveryType, status, hubTrackingNumber, trackingUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HubCreateDeliveryResponse {\n");
    sb.append("    deliveryId: ").append(toIndentedString(deliveryId)).append("\n");
    sb.append("    deliveryType: ").append(toIndentedString(deliveryType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    hubTrackingNumber: ").append(toIndentedString(hubTrackingNumber)).append("\n");
    sb.append("    trackingUrl: ").append(toIndentedString(trackingUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `deliveryId` to the URL query string
    if (getDeliveryId() != null) {
      joiner.add(String.format("%sdeliveryId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeliveryId()))));
    }

    // add `deliveryType` to the URL query string
    if (getDeliveryType() != null) {
      joiner.add(String.format("%sdeliveryType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeliveryType()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format("%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `hubTrackingNumber` to the URL query string
    if (getHubTrackingNumber() != null) {
      joiner.add(String.format("%shubTrackingNumber%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHubTrackingNumber()))));
    }

    // add `trackingUrl` to the URL query string
    if (getTrackingUrl() != null) {
      joiner.add(String.format("%strackingUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTrackingUrl()))));
    }

    return joiner.toString();
  }
}

