/*
 * Service API
 * This API exposes endpoints.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zipper.delivery.hub.sdk.ApiClient;
/**
 * Response after cancelling a delivery
 */
@JsonPropertyOrder({
  HubCancelDeliveryResponse.JSON_PROPERTY_DELIVERY_ID,
  HubCancelDeliveryResponse.JSON_PROPERTY_STATUS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class HubCancelDeliveryResponse {
  public static final String JSON_PROPERTY_DELIVERY_ID = "deliveryId";
  @jakarta.annotation.Nullable
  private UUID deliveryId;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private String status;

  public HubCancelDeliveryResponse() { 
  }

  public HubCancelDeliveryResponse deliveryId(@jakarta.annotation.Nullable UUID deliveryId) {
    this.deliveryId = deliveryId;
    return this;
  }

  /**
   * UUID of the cancelled delivery
   * @return deliveryId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELIVERY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getDeliveryId() {
    return deliveryId;
  }


  @JsonProperty(JSON_PROPERTY_DELIVERY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeliveryId(@jakarta.annotation.Nullable UUID deliveryId) {
    this.deliveryId = deliveryId;
  }


  public HubCancelDeliveryResponse status(@jakarta.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * New delivery status
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable String status) {
    this.status = status;
  }


  /**
   * Return true if this HubCancelDeliveryResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HubCancelDeliveryResponse hubCancelDeliveryResponse = (HubCancelDeliveryResponse) o;
    return Objects.equals(this.deliveryId, hubCancelDeliveryResponse.deliveryId) &&
        Objects.equals(this.status, hubCancelDeliveryResponse.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deliveryId, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HubCancelDeliveryResponse {\n");
    sb.append("    deliveryId: ").append(toIndentedString(deliveryId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `deliveryId` to the URL query string
    if (getDeliveryId() != null) {
      joiner.add(String.format("%sdeliveryId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeliveryId()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format("%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    return joiner.toString();
  }
}

