/*
 * Service API
 * This API exposes endpoints.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zipper.delivery.hub.sdk.model.HandshakeDeliveryDTO;
import com.zipper.delivery.hub.sdk.model.HubContactDTO;
import com.zipper.delivery.hub.sdk.model.HubItemDTO;
import com.zipper.delivery.hub.sdk.model.RecipientDeliveryDTO;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zipper.delivery.hub.sdk.ApiClient;
/**
 * Request to create a new delivery order. A quoteId from a prior quote request is required; pickup and dropoff must match the quoted addresses.
 */
@JsonPropertyOrder({
  HubCreateDeliveryRequest.JSON_PROPERTY_QUOTE_ID,
  HubCreateDeliveryRequest.JSON_PROPERTY_DELIVERY_TYPE,
  HubCreateDeliveryRequest.JSON_PROPERTY_EXTERNAL_ORDER_ID,
  HubCreateDeliveryRequest.JSON_PROPERTY_PICKUP,
  HubCreateDeliveryRequest.JSON_PROPERTY_DROPOFF,
  HubCreateDeliveryRequest.JSON_PROPERTY_ITEMS,
  HubCreateDeliveryRequest.JSON_PROPERTY_COD_AMOUNT,
  HubCreateDeliveryRequest.JSON_PROPERTY_SCHEDULED_AT,
  HubCreateDeliveryRequest.JSON_PROPERTY_SMS_NOTIFICATIONS,
  HubCreateDeliveryRequest.JSON_PROPERTY_HANDSHAKE,
  HubCreateDeliveryRequest.JSON_PROPERTY_RECIPIENT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class HubCreateDeliveryRequest {
  public static final String JSON_PROPERTY_QUOTE_ID = "quoteId";
  @jakarta.annotation.Nonnull
  private UUID quoteId;

  /**
   * Type of delivery
   */
  public enum DeliveryTypeEnum {
    STORE_IMMEDIATE(String.valueOf("STORE_IMMEDIATE")),
    
    FOOD_IMMEDIATE(String.valueOf("FOOD_IMMEDIATE")),
    
    STORE_NEXT_DAY(String.valueOf("STORE_NEXT_DAY"));

    private String value;

    DeliveryTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DeliveryTypeEnum fromValue(String value) {
      for (DeliveryTypeEnum b : DeliveryTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DELIVERY_TYPE = "deliveryType";
  @jakarta.annotation.Nonnull
  private DeliveryTypeEnum deliveryType;

  public static final String JSON_PROPERTY_EXTERNAL_ORDER_ID = "externalOrderId";
  @jakarta.annotation.Nullable
  private String externalOrderId;

  public static final String JSON_PROPERTY_PICKUP = "pickup";
  @jakarta.annotation.Nonnull
  private HubContactDTO pickup;

  public static final String JSON_PROPERTY_DROPOFF = "dropoff";
  @jakarta.annotation.Nonnull
  private HubContactDTO dropoff;

  public static final String JSON_PROPERTY_ITEMS = "items";
  @jakarta.annotation.Nullable
  private List<HubItemDTO> items = new ArrayList<>();

  public static final String JSON_PROPERTY_COD_AMOUNT = "codAmount";
  @jakarta.annotation.Nullable
  private BigDecimal codAmount;

  public static final String JSON_PROPERTY_SCHEDULED_AT = "scheduledAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime scheduledAt;

  public static final String JSON_PROPERTY_SMS_NOTIFICATIONS = "smsNotifications";
  @jakarta.annotation.Nullable
  private Boolean smsNotifications;

  public static final String JSON_PROPERTY_HANDSHAKE = "handshake";
  @jakarta.annotation.Nullable
  private HandshakeDeliveryDTO handshake;

  public static final String JSON_PROPERTY_RECIPIENT = "recipient";
  @jakarta.annotation.Nullable
  private RecipientDeliveryDTO recipient;

  public HubCreateDeliveryRequest() { 
  }

  public HubCreateDeliveryRequest quoteId(@jakarta.annotation.Nonnull UUID quoteId) {
    this.quoteId = quoteId;
    return this;
  }

  /**
   * Quote ID from a prior quote request
   * @return quoteId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_QUOTE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getQuoteId() {
    return quoteId;
  }


  @JsonProperty(JSON_PROPERTY_QUOTE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuoteId(@jakarta.annotation.Nonnull UUID quoteId) {
    this.quoteId = quoteId;
  }


  public HubCreateDeliveryRequest deliveryType(@jakarta.annotation.Nonnull DeliveryTypeEnum deliveryType) {
    this.deliveryType = deliveryType;
    return this;
  }

  /**
   * Type of delivery
   * @return deliveryType
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DELIVERY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public DeliveryTypeEnum getDeliveryType() {
    return deliveryType;
  }


  @JsonProperty(JSON_PROPERTY_DELIVERY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDeliveryType(@jakarta.annotation.Nonnull DeliveryTypeEnum deliveryType) {
    this.deliveryType = deliveryType;
  }


  public HubCreateDeliveryRequest externalOrderId(@jakarta.annotation.Nullable String externalOrderId) {
    this.externalOrderId = externalOrderId;
    return this;
  }

  /**
   * Your external order reference ID
   * @return externalOrderId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTERNAL_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getExternalOrderId() {
    return externalOrderId;
  }


  @JsonProperty(JSON_PROPERTY_EXTERNAL_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalOrderId(@jakarta.annotation.Nullable String externalOrderId) {
    this.externalOrderId = externalOrderId;
  }


  public HubCreateDeliveryRequest pickup(@jakarta.annotation.Nonnull HubContactDTO pickup) {
    this.pickup = pickup;
    return this;
  }

  /**
   * Pickup contact and location
   * @return pickup
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PICKUP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public HubContactDTO getPickup() {
    return pickup;
  }


  @JsonProperty(JSON_PROPERTY_PICKUP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPickup(@jakarta.annotation.Nonnull HubContactDTO pickup) {
    this.pickup = pickup;
  }


  public HubCreateDeliveryRequest dropoff(@jakarta.annotation.Nonnull HubContactDTO dropoff) {
    this.dropoff = dropoff;
    return this;
  }

  /**
   * Dropoff contact and location
   * @return dropoff
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DROPOFF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public HubContactDTO getDropoff() {
    return dropoff;
  }


  @JsonProperty(JSON_PROPERTY_DROPOFF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDropoff(@jakarta.annotation.Nonnull HubContactDTO dropoff) {
    this.dropoff = dropoff;
  }


  public HubCreateDeliveryRequest items(@jakarta.annotation.Nullable List<HubItemDTO> items) {
    this.items = items;
    return this;
  }

  public HubCreateDeliveryRequest addItemsItem(HubItemDTO itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

  /**
   * List of items to deliver
   * @return items
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<HubItemDTO> getItems() {
    return items;
  }


  @JsonProperty(JSON_PROPERTY_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setItems(@jakarta.annotation.Nullable List<HubItemDTO> items) {
    this.items = items;
  }


  public HubCreateDeliveryRequest codAmount(@jakarta.annotation.Nullable BigDecimal codAmount) {
    this.codAmount = codAmount;
    return this;
  }

  /**
   * Cash-on-delivery amount (null if not COD)
   * @return codAmount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COD_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getCodAmount() {
    return codAmount;
  }


  @JsonProperty(JSON_PROPERTY_COD_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCodAmount(@jakarta.annotation.Nullable BigDecimal codAmount) {
    this.codAmount = codAmount;
  }


  public HubCreateDeliveryRequest scheduledAt(@jakarta.annotation.Nullable OffsetDateTime scheduledAt) {
    this.scheduledAt = scheduledAt;
    return this;
  }

  /**
   * Scheduled pickup time (null for immediate dispatch)
   * @return scheduledAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCHEDULED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getScheduledAt() {
    return scheduledAt;
  }


  @JsonProperty(JSON_PROPERTY_SCHEDULED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScheduledAt(@jakarta.annotation.Nullable OffsetDateTime scheduledAt) {
    this.scheduledAt = scheduledAt;
  }


  public HubCreateDeliveryRequest smsNotifications(@jakarta.annotation.Nullable Boolean smsNotifications) {
    this.smsNotifications = smsNotifications;
    return this;
  }

  /**
   * Content for the SMS message(s) which will be sent to the recipient at certain stages of the delivery.  This is an optional feature for communicating the tracking link to the recipient.
   * @return smsNotifications
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SMS_NOTIFICATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getSmsNotifications() {
    return smsNotifications;
  }


  @JsonProperty(JSON_PROPERTY_SMS_NOTIFICATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSmsNotifications(@jakarta.annotation.Nullable Boolean smsNotifications) {
    this.smsNotifications = smsNotifications;
  }


  public HubCreateDeliveryRequest handshake(@jakarta.annotation.Nullable HandshakeDeliveryDTO handshake) {
    this.handshake = handshake;
    return this;
  }

  /**
   * Handshake details for secure delivery. Enables PIN verification on delivery.
   * @return handshake
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HANDSHAKE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public HandshakeDeliveryDTO getHandshake() {
    return handshake;
  }


  @JsonProperty(JSON_PROPERTY_HANDSHAKE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHandshake(@jakarta.annotation.Nullable HandshakeDeliveryDTO handshake) {
    this.handshake = handshake;
  }


  public HubCreateDeliveryRequest recipient(@jakarta.annotation.Nullable RecipientDeliveryDTO recipient) {
    this.recipient = recipient;
    return this;
  }

  /**
   * Details of the recipient who is going to receive the delivery
   * @return recipient
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RECIPIENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public RecipientDeliveryDTO getRecipient() {
    return recipient;
  }


  @JsonProperty(JSON_PROPERTY_RECIPIENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecipient(@jakarta.annotation.Nullable RecipientDeliveryDTO recipient) {
    this.recipient = recipient;
  }


  /**
   * Return true if this HubCreateDeliveryRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HubCreateDeliveryRequest hubCreateDeliveryRequest = (HubCreateDeliveryRequest) o;
    return Objects.equals(this.quoteId, hubCreateDeliveryRequest.quoteId) &&
        Objects.equals(this.deliveryType, hubCreateDeliveryRequest.deliveryType) &&
        Objects.equals(this.externalOrderId, hubCreateDeliveryRequest.externalOrderId) &&
        Objects.equals(this.pickup, hubCreateDeliveryRequest.pickup) &&
        Objects.equals(this.dropoff, hubCreateDeliveryRequest.dropoff) &&
        Objects.equals(this.items, hubCreateDeliveryRequest.items) &&
        Objects.equals(this.codAmount, hubCreateDeliveryRequest.codAmount) &&
        Objects.equals(this.scheduledAt, hubCreateDeliveryRequest.scheduledAt) &&
        Objects.equals(this.smsNotifications, hubCreateDeliveryRequest.smsNotifications) &&
        Objects.equals(this.handshake, hubCreateDeliveryRequest.handshake) &&
        Objects.equals(this.recipient, hubCreateDeliveryRequest.recipient);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quoteId, deliveryType, externalOrderId, pickup, dropoff, items, codAmount, scheduledAt, smsNotifications, handshake, recipient);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HubCreateDeliveryRequest {\n");
    sb.append("    quoteId: ").append(toIndentedString(quoteId)).append("\n");
    sb.append("    deliveryType: ").append(toIndentedString(deliveryType)).append("\n");
    sb.append("    externalOrderId: ").append(toIndentedString(externalOrderId)).append("\n");
    sb.append("    pickup: ").append(toIndentedString(pickup)).append("\n");
    sb.append("    dropoff: ").append(toIndentedString(dropoff)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    codAmount: ").append(toIndentedString(codAmount)).append("\n");
    sb.append("    scheduledAt: ").append(toIndentedString(scheduledAt)).append("\n");
    sb.append("    smsNotifications: ").append(toIndentedString(smsNotifications)).append("\n");
    sb.append("    handshake: ").append(toIndentedString(handshake)).append("\n");
    sb.append("    recipient: ").append(toIndentedString(recipient)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `quoteId` to the URL query string
    if (getQuoteId() != null) {
      joiner.add(String.format("%squoteId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQuoteId()))));
    }

    // add `deliveryType` to the URL query string
    if (getDeliveryType() != null) {
      joiner.add(String.format("%sdeliveryType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeliveryType()))));
    }

    // add `externalOrderId` to the URL query string
    if (getExternalOrderId() != null) {
      joiner.add(String.format("%sexternalOrderId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExternalOrderId()))));
    }

    // add `pickup` to the URL query string
    if (getPickup() != null) {
      joiner.add(getPickup().toUrlQueryString(prefix + "pickup" + suffix));
    }

    // add `dropoff` to the URL query string
    if (getDropoff() != null) {
      joiner.add(getDropoff().toUrlQueryString(prefix + "dropoff" + suffix));
    }

    // add `items` to the URL query string
    if (getItems() != null) {
      for (int i = 0; i < getItems().size(); i++) {
        if (getItems().get(i) != null) {
          joiner.add(getItems().get(i).toUrlQueryString(String.format("%sitems%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `codAmount` to the URL query string
    if (getCodAmount() != null) {
      joiner.add(String.format("%scodAmount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCodAmount()))));
    }

    // add `scheduledAt` to the URL query string
    if (getScheduledAt() != null) {
      joiner.add(String.format("%sscheduledAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getScheduledAt()))));
    }

    // add `smsNotifications` to the URL query string
    if (getSmsNotifications() != null) {
      joiner.add(String.format("%ssmsNotifications%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSmsNotifications()))));
    }

    // add `handshake` to the URL query string
    if (getHandshake() != null) {
      joiner.add(getHandshake().toUrlQueryString(prefix + "handshake" + suffix));
    }

    // add `recipient` to the URL query string
    if (getRecipient() != null) {
      joiner.add(getRecipient().toUrlQueryString(prefix + "recipient" + suffix));
    }

    return joiner.toString();
  }
}

