/*
 * Service API
 * This API exposes endpoints.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zipper.delivery.hub.sdk.model.HubDeliveryLocationDTO;
import com.zipper.delivery.hub.sdk.model.HubItemDTO;
import com.zipper.delivery.hub.sdk.model.HubStatusEventDTO;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zipper.delivery.hub.sdk.ApiClient;
/**
 * Full delivery status including tracking and history
 */
@JsonPropertyOrder({
  HubDeliveryStatusResponse.JSON_PROPERTY_DELIVERY_ID,
  HubDeliveryStatusResponse.JSON_PROPERTY_DELIVERY_TYPE,
  HubDeliveryStatusResponse.JSON_PROPERTY_STATUS,
  HubDeliveryStatusResponse.JSON_PROPERTY_PROVIDER,
  HubDeliveryStatusResponse.JSON_PROPERTY_PROVIDER_TRACKING_ID,
  HubDeliveryStatusResponse.JSON_PROPERTY_HUB_TRACKING_NUMBER,
  HubDeliveryStatusResponse.JSON_PROPERTY_HUB_ORDER_ID,
  HubDeliveryStatusResponse.JSON_PROPERTY_HUB_BARCODE,
  HubDeliveryStatusResponse.JSON_PROPERTY_ESTIMATED_ARRIVAL,
  HubDeliveryStatusResponse.JSON_PROPERTY_TRACKING_URL,
  HubDeliveryStatusResponse.JSON_PROPERTY_STATUS_HISTORY,
  HubDeliveryStatusResponse.JSON_PROPERTY_PROOF_OF_DELIVERY_URL,
  HubDeliveryStatusResponse.JSON_PROPERTY_ITEMS,
  HubDeliveryStatusResponse.JSON_PROPERTY_PICKUP_CONTACT_NAME,
  HubDeliveryStatusResponse.JSON_PROPERTY_PICKUP_CONTACT_PHONE,
  HubDeliveryStatusResponse.JSON_PROPERTY_PICKUP_EMAIL,
  HubDeliveryStatusResponse.JSON_PROPERTY_PICKUP_NOTES,
  HubDeliveryStatusResponse.JSON_PROPERTY_PICKUP_LOCATION,
  HubDeliveryStatusResponse.JSON_PROPERTY_DROPOFF_CONTACT_NAME,
  HubDeliveryStatusResponse.JSON_PROPERTY_DROPOFF_CONTACT_PHONE,
  HubDeliveryStatusResponse.JSON_PROPERTY_DROPOFF_EMAIL,
  HubDeliveryStatusResponse.JSON_PROPERTY_DROPOFF_NOTES,
  HubDeliveryStatusResponse.JSON_PROPERTY_DROPOFF_LOCATION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class HubDeliveryStatusResponse {
  public static final String JSON_PROPERTY_DELIVERY_ID = "deliveryId";
  @jakarta.annotation.Nullable
  private UUID deliveryId;

  /**
   * Type of delivery
   */
  public enum DeliveryTypeEnum {
    STORE_IMMEDIATE(String.valueOf("STORE_IMMEDIATE")),
    
    FOOD_IMMEDIATE(String.valueOf("FOOD_IMMEDIATE")),
    
    STORE_NEXT_DAY(String.valueOf("STORE_NEXT_DAY"));

    private String value;

    DeliveryTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DeliveryTypeEnum fromValue(String value) {
      for (DeliveryTypeEnum b : DeliveryTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DELIVERY_TYPE = "deliveryType";
  @jakarta.annotation.Nullable
  private DeliveryTypeEnum deliveryType;

  /**
   * Current delivery status
   */
  public enum StatusEnum {
    CREATED(String.valueOf("CREATED")),
    
    ASSIGNED(String.valueOf("ASSIGNED")),
    
    READY_FOR_PICKUP(String.valueOf("READY_FOR_PICKUP")),
    
    PICKED_UP(String.valueOf("PICKED_UP")),
    
    IN_TRANSIT(String.valueOf("IN_TRANSIT")),
    
    DELIVERED(String.valueOf("DELIVERED")),
    
    CANCELLED(String.valueOf("CANCELLED")),
    
    FAILED(String.valueOf("FAILED")),
    
    REJECTED(String.valueOf("REJECTED"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private StatusEnum status;

  /**
   * Carrier provider handling the delivery
   */
  public enum ProviderEnum {
    ZIPPERG(String.valueOf("ZIPPERG")),
    
    ZIPPERW(String.valueOf("ZIPPERW")),
    
    ZIPPERK(String.valueOf("ZIPPERK"));

    private String value;

    ProviderEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ProviderEnum fromValue(String value) {
      for (ProviderEnum b : ProviderEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PROVIDER = "provider";
  @jakarta.annotation.Nullable
  private ProviderEnum provider;

  public static final String JSON_PROPERTY_PROVIDER_TRACKING_ID = "providerTrackingId";
  @jakarta.annotation.Nullable
  private String providerTrackingId;

  public static final String JSON_PROPERTY_HUB_TRACKING_NUMBER = "hubTrackingNumber";
  @jakarta.annotation.Nullable
  private String hubTrackingNumber;

  public static final String JSON_PROPERTY_HUB_ORDER_ID = "hubOrderId";
  @jakarta.annotation.Nullable
  private String hubOrderId;

  public static final String JSON_PROPERTY_HUB_BARCODE = "hubBarcode";
  @jakarta.annotation.Nullable
  private String hubBarcode;

  public static final String JSON_PROPERTY_ESTIMATED_ARRIVAL = "estimatedArrival";
  @jakarta.annotation.Nullable
  private OffsetDateTime estimatedArrival;

  public static final String JSON_PROPERTY_TRACKING_URL = "trackingUrl";
  @jakarta.annotation.Nullable
  private String trackingUrl;

  public static final String JSON_PROPERTY_STATUS_HISTORY = "statusHistory";
  @jakarta.annotation.Nullable
  private List<HubStatusEventDTO> statusHistory = new ArrayList<>();

  public static final String JSON_PROPERTY_PROOF_OF_DELIVERY_URL = "proofOfDeliveryUrl";
  @jakarta.annotation.Nullable
  private String proofOfDeliveryUrl;

  public static final String JSON_PROPERTY_ITEMS = "items";
  @jakarta.annotation.Nullable
  private List<HubItemDTO> items = new ArrayList<>();

  public static final String JSON_PROPERTY_PICKUP_CONTACT_NAME = "pickupContactName";
  @jakarta.annotation.Nullable
  private String pickupContactName;

  public static final String JSON_PROPERTY_PICKUP_CONTACT_PHONE = "pickupContactPhone";
  @jakarta.annotation.Nullable
  private String pickupContactPhone;

  public static final String JSON_PROPERTY_PICKUP_EMAIL = "pickupEmail";
  @jakarta.annotation.Nullable
  private String pickupEmail;

  public static final String JSON_PROPERTY_PICKUP_NOTES = "pickupNotes";
  @jakarta.annotation.Nullable
  private String pickupNotes;

  public static final String JSON_PROPERTY_PICKUP_LOCATION = "pickupLocation";
  @jakarta.annotation.Nullable
  private HubDeliveryLocationDTO pickupLocation;

  public static final String JSON_PROPERTY_DROPOFF_CONTACT_NAME = "dropoffContactName";
  @jakarta.annotation.Nullable
  private String dropoffContactName;

  public static final String JSON_PROPERTY_DROPOFF_CONTACT_PHONE = "dropoffContactPhone";
  @jakarta.annotation.Nullable
  private String dropoffContactPhone;

  public static final String JSON_PROPERTY_DROPOFF_EMAIL = "dropoffEmail";
  @jakarta.annotation.Nullable
  private String dropoffEmail;

  public static final String JSON_PROPERTY_DROPOFF_NOTES = "dropoffNotes";
  @jakarta.annotation.Nullable
  private String dropoffNotes;

  public static final String JSON_PROPERTY_DROPOFF_LOCATION = "dropoffLocation";
  @jakarta.annotation.Nullable
  private HubDeliveryLocationDTO dropoffLocation;

  public HubDeliveryStatusResponse() { 
  }

  public HubDeliveryStatusResponse deliveryId(@jakarta.annotation.Nullable UUID deliveryId) {
    this.deliveryId = deliveryId;
    return this;
  }

  /**
   * Unique delivery identifier
   * @return deliveryId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELIVERY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getDeliveryId() {
    return deliveryId;
  }


  @JsonProperty(JSON_PROPERTY_DELIVERY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeliveryId(@jakarta.annotation.Nullable UUID deliveryId) {
    this.deliveryId = deliveryId;
  }


  public HubDeliveryStatusResponse deliveryType(@jakarta.annotation.Nullable DeliveryTypeEnum deliveryType) {
    this.deliveryType = deliveryType;
    return this;
  }

  /**
   * Type of delivery
   * @return deliveryType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELIVERY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public DeliveryTypeEnum getDeliveryType() {
    return deliveryType;
  }


  @JsonProperty(JSON_PROPERTY_DELIVERY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeliveryType(@jakarta.annotation.Nullable DeliveryTypeEnum deliveryType) {
    this.deliveryType = deliveryType;
  }


  public HubDeliveryStatusResponse status(@jakarta.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Current delivery status
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public HubDeliveryStatusResponse provider(@jakarta.annotation.Nullable ProviderEnum provider) {
    this.provider = provider;
    return this;
  }

  /**
   * Carrier provider handling the delivery
   * @return provider
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ProviderEnum getProvider() {
    return provider;
  }


  @JsonProperty(JSON_PROPERTY_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProvider(@jakarta.annotation.Nullable ProviderEnum provider) {
    this.provider = provider;
  }


  public HubDeliveryStatusResponse providerTrackingId(@jakarta.annotation.Nullable String providerTrackingId) {
    this.providerTrackingId = providerTrackingId;
    return this;
  }

  /**
   * Tracking ID from the carrier provider
   * @return providerTrackingId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROVIDER_TRACKING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProviderTrackingId() {
    return providerTrackingId;
  }


  @JsonProperty(JSON_PROPERTY_PROVIDER_TRACKING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProviderTrackingId(@jakarta.annotation.Nullable String providerTrackingId) {
    this.providerTrackingId = providerTrackingId;
  }


  public HubDeliveryStatusResponse hubTrackingNumber(@jakarta.annotation.Nullable String hubTrackingNumber) {
    this.hubTrackingNumber = hubTrackingNumber;
    return this;
  }

  /**
   * Hub tracking number
   * @return hubTrackingNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HUB_TRACKING_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHubTrackingNumber() {
    return hubTrackingNumber;
  }


  @JsonProperty(JSON_PROPERTY_HUB_TRACKING_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHubTrackingNumber(@jakarta.annotation.Nullable String hubTrackingNumber) {
    this.hubTrackingNumber = hubTrackingNumber;
  }


  public HubDeliveryStatusResponse hubOrderId(@jakarta.annotation.Nullable String hubOrderId) {
    this.hubOrderId = hubOrderId;
    return this;
  }

  /**
   * Hub order ID
   * @return hubOrderId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HUB_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHubOrderId() {
    return hubOrderId;
  }


  @JsonProperty(JSON_PROPERTY_HUB_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHubOrderId(@jakarta.annotation.Nullable String hubOrderId) {
    this.hubOrderId = hubOrderId;
  }


  public HubDeliveryStatusResponse hubBarcode(@jakarta.annotation.Nullable String hubBarcode) {
    this.hubBarcode = hubBarcode;
    return this;
  }

  /**
   * Hub barcode
   * @return hubBarcode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HUB_BARCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHubBarcode() {
    return hubBarcode;
  }


  @JsonProperty(JSON_PROPERTY_HUB_BARCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHubBarcode(@jakarta.annotation.Nullable String hubBarcode) {
    this.hubBarcode = hubBarcode;
  }


  public HubDeliveryStatusResponse estimatedArrival(@jakarta.annotation.Nullable OffsetDateTime estimatedArrival) {
    this.estimatedArrival = estimatedArrival;
    return this;
  }

  /**
   * Estimated arrival time
   * @return estimatedArrival
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ESTIMATED_ARRIVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getEstimatedArrival() {
    return estimatedArrival;
  }


  @JsonProperty(JSON_PROPERTY_ESTIMATED_ARRIVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEstimatedArrival(@jakarta.annotation.Nullable OffsetDateTime estimatedArrival) {
    this.estimatedArrival = estimatedArrival;
  }


  public HubDeliveryStatusResponse trackingUrl(@jakarta.annotation.Nullable String trackingUrl) {
    this.trackingUrl = trackingUrl;
    return this;
  }

  /**
   * Public tracking URL for the delivery recipient
   * @return trackingUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRACKING_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTrackingUrl() {
    return trackingUrl;
  }


  @JsonProperty(JSON_PROPERTY_TRACKING_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackingUrl(@jakarta.annotation.Nullable String trackingUrl) {
    this.trackingUrl = trackingUrl;
  }


  public HubDeliveryStatusResponse statusHistory(@jakarta.annotation.Nullable List<HubStatusEventDTO> statusHistory) {
    this.statusHistory = statusHistory;
    return this;
  }

  public HubDeliveryStatusResponse addStatusHistoryItem(HubStatusEventDTO statusHistoryItem) {
    if (this.statusHistory == null) {
      this.statusHistory = new ArrayList<>();
    }
    this.statusHistory.add(statusHistoryItem);
    return this;
  }

  /**
   * Chronological list of status changes
   * @return statusHistory
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS_HISTORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<HubStatusEventDTO> getStatusHistory() {
    return statusHistory;
  }


  @JsonProperty(JSON_PROPERTY_STATUS_HISTORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatusHistory(@jakarta.annotation.Nullable List<HubStatusEventDTO> statusHistory) {
    this.statusHistory = statusHistory;
  }


  public HubDeliveryStatusResponse proofOfDeliveryUrl(@jakarta.annotation.Nullable String proofOfDeliveryUrl) {
    this.proofOfDeliveryUrl = proofOfDeliveryUrl;
    return this;
  }

  /**
   * URL to the proof-of-delivery image (available after delivery)
   * @return proofOfDeliveryUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROOF_OF_DELIVERY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProofOfDeliveryUrl() {
    return proofOfDeliveryUrl;
  }


  @JsonProperty(JSON_PROPERTY_PROOF_OF_DELIVERY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProofOfDeliveryUrl(@jakarta.annotation.Nullable String proofOfDeliveryUrl) {
    this.proofOfDeliveryUrl = proofOfDeliveryUrl;
  }


  public HubDeliveryStatusResponse items(@jakarta.annotation.Nullable List<HubItemDTO> items) {
    this.items = items;
    return this;
  }

  public HubDeliveryStatusResponse addItemsItem(HubItemDTO itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

  /**
   * Items included in the delivery
   * @return items
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<HubItemDTO> getItems() {
    return items;
  }


  @JsonProperty(JSON_PROPERTY_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setItems(@jakarta.annotation.Nullable List<HubItemDTO> items) {
    this.items = items;
  }


  public HubDeliveryStatusResponse pickupContactName(@jakarta.annotation.Nullable String pickupContactName) {
    this.pickupContactName = pickupContactName;
    return this;
  }

  /**
   * Pickup contact name
   * @return pickupContactName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PICKUP_CONTACT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPickupContactName() {
    return pickupContactName;
  }


  @JsonProperty(JSON_PROPERTY_PICKUP_CONTACT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPickupContactName(@jakarta.annotation.Nullable String pickupContactName) {
    this.pickupContactName = pickupContactName;
  }


  public HubDeliveryStatusResponse pickupContactPhone(@jakarta.annotation.Nullable String pickupContactPhone) {
    this.pickupContactPhone = pickupContactPhone;
    return this;
  }

  /**
   * Pickup contact phone number
   * @return pickupContactPhone
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PICKUP_CONTACT_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPickupContactPhone() {
    return pickupContactPhone;
  }


  @JsonProperty(JSON_PROPERTY_PICKUP_CONTACT_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPickupContactPhone(@jakarta.annotation.Nullable String pickupContactPhone) {
    this.pickupContactPhone = pickupContactPhone;
  }


  public HubDeliveryStatusResponse pickupEmail(@jakarta.annotation.Nullable String pickupEmail) {
    this.pickupEmail = pickupEmail;
    return this;
  }

  /**
   * Pickup contact email
   * @return pickupEmail
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PICKUP_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPickupEmail() {
    return pickupEmail;
  }


  @JsonProperty(JSON_PROPERTY_PICKUP_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPickupEmail(@jakarta.annotation.Nullable String pickupEmail) {
    this.pickupEmail = pickupEmail;
  }


  public HubDeliveryStatusResponse pickupNotes(@jakarta.annotation.Nullable String pickupNotes) {
    this.pickupNotes = pickupNotes;
    return this;
  }

  /**
   * Pickup notes or instructions
   * @return pickupNotes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PICKUP_NOTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPickupNotes() {
    return pickupNotes;
  }


  @JsonProperty(JSON_PROPERTY_PICKUP_NOTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPickupNotes(@jakarta.annotation.Nullable String pickupNotes) {
    this.pickupNotes = pickupNotes;
  }


  public HubDeliveryStatusResponse pickupLocation(@jakarta.annotation.Nullable HubDeliveryLocationDTO pickupLocation) {
    this.pickupLocation = pickupLocation;
    return this;
  }

  /**
   * Pickup location details
   * @return pickupLocation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PICKUP_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public HubDeliveryLocationDTO getPickupLocation() {
    return pickupLocation;
  }


  @JsonProperty(JSON_PROPERTY_PICKUP_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPickupLocation(@jakarta.annotation.Nullable HubDeliveryLocationDTO pickupLocation) {
    this.pickupLocation = pickupLocation;
  }


  public HubDeliveryStatusResponse dropoffContactName(@jakarta.annotation.Nullable String dropoffContactName) {
    this.dropoffContactName = dropoffContactName;
    return this;
  }

  /**
   * Dropoff contact name
   * @return dropoffContactName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DROPOFF_CONTACT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDropoffContactName() {
    return dropoffContactName;
  }


  @JsonProperty(JSON_PROPERTY_DROPOFF_CONTACT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDropoffContactName(@jakarta.annotation.Nullable String dropoffContactName) {
    this.dropoffContactName = dropoffContactName;
  }


  public HubDeliveryStatusResponse dropoffContactPhone(@jakarta.annotation.Nullable String dropoffContactPhone) {
    this.dropoffContactPhone = dropoffContactPhone;
    return this;
  }

  /**
   * Dropoff contact phone number
   * @return dropoffContactPhone
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DROPOFF_CONTACT_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDropoffContactPhone() {
    return dropoffContactPhone;
  }


  @JsonProperty(JSON_PROPERTY_DROPOFF_CONTACT_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDropoffContactPhone(@jakarta.annotation.Nullable String dropoffContactPhone) {
    this.dropoffContactPhone = dropoffContactPhone;
  }


  public HubDeliveryStatusResponse dropoffEmail(@jakarta.annotation.Nullable String dropoffEmail) {
    this.dropoffEmail = dropoffEmail;
    return this;
  }

  /**
   * Dropoff contact email
   * @return dropoffEmail
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DROPOFF_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDropoffEmail() {
    return dropoffEmail;
  }


  @JsonProperty(JSON_PROPERTY_DROPOFF_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDropoffEmail(@jakarta.annotation.Nullable String dropoffEmail) {
    this.dropoffEmail = dropoffEmail;
  }


  public HubDeliveryStatusResponse dropoffNotes(@jakarta.annotation.Nullable String dropoffNotes) {
    this.dropoffNotes = dropoffNotes;
    return this;
  }

  /**
   * Dropoff notes or instructions
   * @return dropoffNotes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DROPOFF_NOTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDropoffNotes() {
    return dropoffNotes;
  }


  @JsonProperty(JSON_PROPERTY_DROPOFF_NOTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDropoffNotes(@jakarta.annotation.Nullable String dropoffNotes) {
    this.dropoffNotes = dropoffNotes;
  }


  public HubDeliveryStatusResponse dropoffLocation(@jakarta.annotation.Nullable HubDeliveryLocationDTO dropoffLocation) {
    this.dropoffLocation = dropoffLocation;
    return this;
  }

  /**
   * Dropoff location details
   * @return dropoffLocation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DROPOFF_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public HubDeliveryLocationDTO getDropoffLocation() {
    return dropoffLocation;
  }


  @JsonProperty(JSON_PROPERTY_DROPOFF_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDropoffLocation(@jakarta.annotation.Nullable HubDeliveryLocationDTO dropoffLocation) {
    this.dropoffLocation = dropoffLocation;
  }


  /**
   * Return true if this HubDeliveryStatusResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HubDeliveryStatusResponse hubDeliveryStatusResponse = (HubDeliveryStatusResponse) o;
    return Objects.equals(this.deliveryId, hubDeliveryStatusResponse.deliveryId) &&
        Objects.equals(this.deliveryType, hubDeliveryStatusResponse.deliveryType) &&
        Objects.equals(this.status, hubDeliveryStatusResponse.status) &&
        Objects.equals(this.provider, hubDeliveryStatusResponse.provider) &&
        Objects.equals(this.providerTrackingId, hubDeliveryStatusResponse.providerTrackingId) &&
        Objects.equals(this.hubTrackingNumber, hubDeliveryStatusResponse.hubTrackingNumber) &&
        Objects.equals(this.hubOrderId, hubDeliveryStatusResponse.hubOrderId) &&
        Objects.equals(this.hubBarcode, hubDeliveryStatusResponse.hubBarcode) &&
        Objects.equals(this.estimatedArrival, hubDeliveryStatusResponse.estimatedArrival) &&
        Objects.equals(this.trackingUrl, hubDeliveryStatusResponse.trackingUrl) &&
        Objects.equals(this.statusHistory, hubDeliveryStatusResponse.statusHistory) &&
        Objects.equals(this.proofOfDeliveryUrl, hubDeliveryStatusResponse.proofOfDeliveryUrl) &&
        Objects.equals(this.items, hubDeliveryStatusResponse.items) &&
        Objects.equals(this.pickupContactName, hubDeliveryStatusResponse.pickupContactName) &&
        Objects.equals(this.pickupContactPhone, hubDeliveryStatusResponse.pickupContactPhone) &&
        Objects.equals(this.pickupEmail, hubDeliveryStatusResponse.pickupEmail) &&
        Objects.equals(this.pickupNotes, hubDeliveryStatusResponse.pickupNotes) &&
        Objects.equals(this.pickupLocation, hubDeliveryStatusResponse.pickupLocation) &&
        Objects.equals(this.dropoffContactName, hubDeliveryStatusResponse.dropoffContactName) &&
        Objects.equals(this.dropoffContactPhone, hubDeliveryStatusResponse.dropoffContactPhone) &&
        Objects.equals(this.dropoffEmail, hubDeliveryStatusResponse.dropoffEmail) &&
        Objects.equals(this.dropoffNotes, hubDeliveryStatusResponse.dropoffNotes) &&
        Objects.equals(this.dropoffLocation, hubDeliveryStatusResponse.dropoffLocation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deliveryId, deliveryType, status, provider, providerTrackingId, hubTrackingNumber, hubOrderId, hubBarcode, estimatedArrival, trackingUrl, statusHistory, proofOfDeliveryUrl, items, pickupContactName, pickupContactPhone, pickupEmail, pickupNotes, pickupLocation, dropoffContactName, dropoffContactPhone, dropoffEmail, dropoffNotes, dropoffLocation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HubDeliveryStatusResponse {\n");
    sb.append("    deliveryId: ").append(toIndentedString(deliveryId)).append("\n");
    sb.append("    deliveryType: ").append(toIndentedString(deliveryType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    providerTrackingId: ").append(toIndentedString(providerTrackingId)).append("\n");
    sb.append("    hubTrackingNumber: ").append(toIndentedString(hubTrackingNumber)).append("\n");
    sb.append("    hubOrderId: ").append(toIndentedString(hubOrderId)).append("\n");
    sb.append("    hubBarcode: ").append(toIndentedString(hubBarcode)).append("\n");
    sb.append("    estimatedArrival: ").append(toIndentedString(estimatedArrival)).append("\n");
    sb.append("    trackingUrl: ").append(toIndentedString(trackingUrl)).append("\n");
    sb.append("    statusHistory: ").append(toIndentedString(statusHistory)).append("\n");
    sb.append("    proofOfDeliveryUrl: ").append(toIndentedString(proofOfDeliveryUrl)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    pickupContactName: ").append(toIndentedString(pickupContactName)).append("\n");
    sb.append("    pickupContactPhone: ").append(toIndentedString(pickupContactPhone)).append("\n");
    sb.append("    pickupEmail: ").append(toIndentedString(pickupEmail)).append("\n");
    sb.append("    pickupNotes: ").append(toIndentedString(pickupNotes)).append("\n");
    sb.append("    pickupLocation: ").append(toIndentedString(pickupLocation)).append("\n");
    sb.append("    dropoffContactName: ").append(toIndentedString(dropoffContactName)).append("\n");
    sb.append("    dropoffContactPhone: ").append(toIndentedString(dropoffContactPhone)).append("\n");
    sb.append("    dropoffEmail: ").append(toIndentedString(dropoffEmail)).append("\n");
    sb.append("    dropoffNotes: ").append(toIndentedString(dropoffNotes)).append("\n");
    sb.append("    dropoffLocation: ").append(toIndentedString(dropoffLocation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `deliveryId` to the URL query string
    if (getDeliveryId() != null) {
      joiner.add(String.format("%sdeliveryId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeliveryId()))));
    }

    // add `deliveryType` to the URL query string
    if (getDeliveryType() != null) {
      joiner.add(String.format("%sdeliveryType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeliveryType()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format("%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `provider` to the URL query string
    if (getProvider() != null) {
      joiner.add(String.format("%sprovider%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProvider()))));
    }

    // add `providerTrackingId` to the URL query string
    if (getProviderTrackingId() != null) {
      joiner.add(String.format("%sproviderTrackingId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProviderTrackingId()))));
    }

    // add `hubTrackingNumber` to the URL query string
    if (getHubTrackingNumber() != null) {
      joiner.add(String.format("%shubTrackingNumber%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHubTrackingNumber()))));
    }

    // add `hubOrderId` to the URL query string
    if (getHubOrderId() != null) {
      joiner.add(String.format("%shubOrderId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHubOrderId()))));
    }

    // add `hubBarcode` to the URL query string
    if (getHubBarcode() != null) {
      joiner.add(String.format("%shubBarcode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHubBarcode()))));
    }

    // add `estimatedArrival` to the URL query string
    if (getEstimatedArrival() != null) {
      joiner.add(String.format("%sestimatedArrival%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEstimatedArrival()))));
    }

    // add `trackingUrl` to the URL query string
    if (getTrackingUrl() != null) {
      joiner.add(String.format("%strackingUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTrackingUrl()))));
    }

    // add `statusHistory` to the URL query string
    if (getStatusHistory() != null) {
      for (int i = 0; i < getStatusHistory().size(); i++) {
        if (getStatusHistory().get(i) != null) {
          joiner.add(getStatusHistory().get(i).toUrlQueryString(String.format("%sstatusHistory%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `proofOfDeliveryUrl` to the URL query string
    if (getProofOfDeliveryUrl() != null) {
      joiner.add(String.format("%sproofOfDeliveryUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProofOfDeliveryUrl()))));
    }

    // add `items` to the URL query string
    if (getItems() != null) {
      for (int i = 0; i < getItems().size(); i++) {
        if (getItems().get(i) != null) {
          joiner.add(getItems().get(i).toUrlQueryString(String.format("%sitems%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `pickupContactName` to the URL query string
    if (getPickupContactName() != null) {
      joiner.add(String.format("%spickupContactName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPickupContactName()))));
    }

    // add `pickupContactPhone` to the URL query string
    if (getPickupContactPhone() != null) {
      joiner.add(String.format("%spickupContactPhone%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPickupContactPhone()))));
    }

    // add `pickupEmail` to the URL query string
    if (getPickupEmail() != null) {
      joiner.add(String.format("%spickupEmail%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPickupEmail()))));
    }

    // add `pickupNotes` to the URL query string
    if (getPickupNotes() != null) {
      joiner.add(String.format("%spickupNotes%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPickupNotes()))));
    }

    // add `pickupLocation` to the URL query string
    if (getPickupLocation() != null) {
      joiner.add(getPickupLocation().toUrlQueryString(prefix + "pickupLocation" + suffix));
    }

    // add `dropoffContactName` to the URL query string
    if (getDropoffContactName() != null) {
      joiner.add(String.format("%sdropoffContactName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDropoffContactName()))));
    }

    // add `dropoffContactPhone` to the URL query string
    if (getDropoffContactPhone() != null) {
      joiner.add(String.format("%sdropoffContactPhone%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDropoffContactPhone()))));
    }

    // add `dropoffEmail` to the URL query string
    if (getDropoffEmail() != null) {
      joiner.add(String.format("%sdropoffEmail%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDropoffEmail()))));
    }

    // add `dropoffNotes` to the URL query string
    if (getDropoffNotes() != null) {
      joiner.add(String.format("%sdropoffNotes%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDropoffNotes()))));
    }

    // add `dropoffLocation` to the URL query string
    if (getDropoffLocation() != null) {
      joiner.add(getDropoffLocation().toUrlQueryString(prefix + "dropoffLocation" + suffix));
    }

    return joiner.toString();
  }
}

