/*
 * Service API
 * This API exposes endpoints.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zipper.delivery.hub.sdk.ApiClient;
/**
 * Delivery price quote from a carrier provider
 */
@JsonPropertyOrder({
  HubDeliveryQuoteResponse.JSON_PROPERTY_DELIVERY_TYPE,
  HubDeliveryQuoteResponse.JSON_PROPERTY_PROVIDER,
  HubDeliveryQuoteResponse.JSON_PROPERTY_PRICE,
  HubDeliveryQuoteResponse.JSON_PROPERTY_CURRENCY,
  HubDeliveryQuoteResponse.JSON_PROPERTY_ESTIMATED_ARRIVAL_SECONDS,
  HubDeliveryQuoteResponse.JSON_PROPERTY_QUOTE_ID,
  HubDeliveryQuoteResponse.JSON_PROPERTY_DISTANCE_METERS,
  HubDeliveryQuoteResponse.JSON_PROPERTY_DURATION_SECONDS,
  HubDeliveryQuoteResponse.JSON_PROPERTY_EXPIRES_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class HubDeliveryQuoteResponse {
  /**
   * Type of delivery
   */
  public enum DeliveryTypeEnum {
    STORE_IMMEDIATE(String.valueOf("STORE_IMMEDIATE")),
    
    FOOD_IMMEDIATE(String.valueOf("FOOD_IMMEDIATE")),
    
    STORE_NEXT_DAY(String.valueOf("STORE_NEXT_DAY"));

    private String value;

    DeliveryTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DeliveryTypeEnum fromValue(String value) {
      for (DeliveryTypeEnum b : DeliveryTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DELIVERY_TYPE = "deliveryType";
  @jakarta.annotation.Nullable
  private DeliveryTypeEnum deliveryType;

  /**
   * Carrier provider name
   */
  public enum ProviderEnum {
    ZIPPERG(String.valueOf("ZIPPERG")),
    
    ZIPPERW(String.valueOf("ZIPPERW")),
    
    ZIPPERK(String.valueOf("ZIPPERK"));

    private String value;

    ProviderEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ProviderEnum fromValue(String value) {
      for (ProviderEnum b : ProviderEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PROVIDER = "provider";
  @jakarta.annotation.Nullable
  private ProviderEnum provider;

  public static final String JSON_PROPERTY_PRICE = "price";
  @jakarta.annotation.Nullable
  private BigDecimal price;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @jakarta.annotation.Nullable
  private String currency;

  public static final String JSON_PROPERTY_ESTIMATED_ARRIVAL_SECONDS = "estimatedArrivalSeconds";
  @jakarta.annotation.Nullable
  private Integer estimatedArrivalSeconds;

  public static final String JSON_PROPERTY_QUOTE_ID = "quoteId";
  @jakarta.annotation.Nullable
  private UUID quoteId;

  public static final String JSON_PROPERTY_DISTANCE_METERS = "distanceMeters";
  @jakarta.annotation.Nullable
  private Long distanceMeters;

  public static final String JSON_PROPERTY_DURATION_SECONDS = "durationSeconds";
  @jakarta.annotation.Nullable
  private Long durationSeconds;

  public static final String JSON_PROPERTY_EXPIRES_AT = "expiresAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime expiresAt;

  public HubDeliveryQuoteResponse() { 
  }

  public HubDeliveryQuoteResponse deliveryType(@jakarta.annotation.Nullable DeliveryTypeEnum deliveryType) {
    this.deliveryType = deliveryType;
    return this;
  }

  /**
   * Type of delivery
   * @return deliveryType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELIVERY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public DeliveryTypeEnum getDeliveryType() {
    return deliveryType;
  }


  @JsonProperty(JSON_PROPERTY_DELIVERY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeliveryType(@jakarta.annotation.Nullable DeliveryTypeEnum deliveryType) {
    this.deliveryType = deliveryType;
  }


  public HubDeliveryQuoteResponse provider(@jakarta.annotation.Nullable ProviderEnum provider) {
    this.provider = provider;
    return this;
  }

  /**
   * Carrier provider name
   * @return provider
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ProviderEnum getProvider() {
    return provider;
  }


  @JsonProperty(JSON_PROPERTY_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProvider(@jakarta.annotation.Nullable ProviderEnum provider) {
    this.provider = provider;
  }


  public HubDeliveryQuoteResponse price(@jakarta.annotation.Nullable BigDecimal price) {
    this.price = price;
    return this;
  }

  /**
   * Quoted delivery price
   * @return price
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getPrice() {
    return price;
  }


  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrice(@jakarta.annotation.Nullable BigDecimal price) {
    this.price = price;
  }


  public HubDeliveryQuoteResponse currency(@jakarta.annotation.Nullable String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Price currency code
   * @return currency
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCurrency() {
    return currency;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrency(@jakarta.annotation.Nullable String currency) {
    this.currency = currency;
  }


  public HubDeliveryQuoteResponse estimatedArrivalSeconds(@jakarta.annotation.Nullable Integer estimatedArrivalSeconds) {
    this.estimatedArrivalSeconds = estimatedArrivalSeconds;
    return this;
  }

  /**
   * Estimated time of arrival in seconds
   * @return estimatedArrivalSeconds
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ESTIMATED_ARRIVAL_SECONDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getEstimatedArrivalSeconds() {
    return estimatedArrivalSeconds;
  }


  @JsonProperty(JSON_PROPERTY_ESTIMATED_ARRIVAL_SECONDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEstimatedArrivalSeconds(@jakarta.annotation.Nullable Integer estimatedArrivalSeconds) {
    this.estimatedArrivalSeconds = estimatedArrivalSeconds;
  }


  public HubDeliveryQuoteResponse quoteId(@jakarta.annotation.Nullable UUID quoteId) {
    this.quoteId = quoteId;
    return this;
  }

  /**
   * Internal quote identifier for use when creating a delivery
   * @return quoteId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUOTE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getQuoteId() {
    return quoteId;
  }


  @JsonProperty(JSON_PROPERTY_QUOTE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuoteId(@jakarta.annotation.Nullable UUID quoteId) {
    this.quoteId = quoteId;
  }


  public HubDeliveryQuoteResponse distanceMeters(@jakarta.annotation.Nullable Long distanceMeters) {
    this.distanceMeters = distanceMeters;
    return this;
  }

  /**
   * Distance between pickup and dropoff in meters
   * @return distanceMeters
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISTANCE_METERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getDistanceMeters() {
    return distanceMeters;
  }


  @JsonProperty(JSON_PROPERTY_DISTANCE_METERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDistanceMeters(@jakarta.annotation.Nullable Long distanceMeters) {
    this.distanceMeters = distanceMeters;
  }


  public HubDeliveryQuoteResponse durationSeconds(@jakarta.annotation.Nullable Long durationSeconds) {
    this.durationSeconds = durationSeconds;
    return this;
  }

  /**
   * Estimated travel duration in seconds
   * @return durationSeconds
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DURATION_SECONDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getDurationSeconds() {
    return durationSeconds;
  }


  @JsonProperty(JSON_PROPERTY_DURATION_SECONDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDurationSeconds(@jakarta.annotation.Nullable Long durationSeconds) {
    this.durationSeconds = durationSeconds;
  }


  public HubDeliveryQuoteResponse expiresAt(@jakarta.annotation.Nullable OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Quote expiration time — create delivery before this time
   * @return expiresAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPIRES_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRES_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiresAt(@jakarta.annotation.Nullable OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }


  /**
   * Return true if this HubDeliveryQuoteResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HubDeliveryQuoteResponse hubDeliveryQuoteResponse = (HubDeliveryQuoteResponse) o;
    return Objects.equals(this.deliveryType, hubDeliveryQuoteResponse.deliveryType) &&
        Objects.equals(this.provider, hubDeliveryQuoteResponse.provider) &&
        Objects.equals(this.price, hubDeliveryQuoteResponse.price) &&
        Objects.equals(this.currency, hubDeliveryQuoteResponse.currency) &&
        Objects.equals(this.estimatedArrivalSeconds, hubDeliveryQuoteResponse.estimatedArrivalSeconds) &&
        Objects.equals(this.quoteId, hubDeliveryQuoteResponse.quoteId) &&
        Objects.equals(this.distanceMeters, hubDeliveryQuoteResponse.distanceMeters) &&
        Objects.equals(this.durationSeconds, hubDeliveryQuoteResponse.durationSeconds) &&
        Objects.equals(this.expiresAt, hubDeliveryQuoteResponse.expiresAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deliveryType, provider, price, currency, estimatedArrivalSeconds, quoteId, distanceMeters, durationSeconds, expiresAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HubDeliveryQuoteResponse {\n");
    sb.append("    deliveryType: ").append(toIndentedString(deliveryType)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    estimatedArrivalSeconds: ").append(toIndentedString(estimatedArrivalSeconds)).append("\n");
    sb.append("    quoteId: ").append(toIndentedString(quoteId)).append("\n");
    sb.append("    distanceMeters: ").append(toIndentedString(distanceMeters)).append("\n");
    sb.append("    durationSeconds: ").append(toIndentedString(durationSeconds)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `deliveryType` to the URL query string
    if (getDeliveryType() != null) {
      joiner.add(String.format("%sdeliveryType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeliveryType()))));
    }

    // add `provider` to the URL query string
    if (getProvider() != null) {
      joiner.add(String.format("%sprovider%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProvider()))));
    }

    // add `price` to the URL query string
    if (getPrice() != null) {
      joiner.add(String.format("%sprice%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPrice()))));
    }

    // add `currency` to the URL query string
    if (getCurrency() != null) {
      joiner.add(String.format("%scurrency%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCurrency()))));
    }

    // add `estimatedArrivalSeconds` to the URL query string
    if (getEstimatedArrivalSeconds() != null) {
      joiner.add(String.format("%sestimatedArrivalSeconds%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEstimatedArrivalSeconds()))));
    }

    // add `quoteId` to the URL query string
    if (getQuoteId() != null) {
      joiner.add(String.format("%squoteId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQuoteId()))));
    }

    // add `distanceMeters` to the URL query string
    if (getDistanceMeters() != null) {
      joiner.add(String.format("%sdistanceMeters%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDistanceMeters()))));
    }

    // add `durationSeconds` to the URL query string
    if (getDurationSeconds() != null) {
      joiner.add(String.format("%sdurationSeconds%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDurationSeconds()))));
    }

    // add `expiresAt` to the URL query string
    if (getExpiresAt() != null) {
      joiner.add(String.format("%sexpiresAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExpiresAt()))));
    }

    return joiner.toString();
  }
}

