/*
 * Service API
 * This API exposes endpoints.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zipper.delivery.hub.sdk.model.HubContactDTO;
import com.zipper.delivery.hub.sdk.model.HubItemDTO;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zipper.delivery.hub.sdk.ApiClient;
/**
 * Request to get a delivery price quote
 */
@JsonPropertyOrder({
  HubDeliveryQuoteRequest.JSON_PROPERTY_DELIVERY_TYPE,
  HubDeliveryQuoteRequest.JSON_PROPERTY_PICKUP,
  HubDeliveryQuoteRequest.JSON_PROPERTY_DROPOFF,
  HubDeliveryQuoteRequest.JSON_PROPERTY_ITEMS,
  HubDeliveryQuoteRequest.JSON_PROPERTY_SCHEDULED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class HubDeliveryQuoteRequest {
  /**
   * Type of delivery
   */
  public enum DeliveryTypeEnum {
    STORE_IMMEDIATE(String.valueOf("STORE_IMMEDIATE")),
    
    FOOD_IMMEDIATE(String.valueOf("FOOD_IMMEDIATE")),
    
    STORE_NEXT_DAY(String.valueOf("STORE_NEXT_DAY"));

    private String value;

    DeliveryTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DeliveryTypeEnum fromValue(String value) {
      for (DeliveryTypeEnum b : DeliveryTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DELIVERY_TYPE = "deliveryType";
  @jakarta.annotation.Nonnull
  private DeliveryTypeEnum deliveryType;

  public static final String JSON_PROPERTY_PICKUP = "pickup";
  @jakarta.annotation.Nonnull
  private HubContactDTO pickup;

  public static final String JSON_PROPERTY_DROPOFF = "dropoff";
  @jakarta.annotation.Nonnull
  private HubContactDTO dropoff;

  public static final String JSON_PROPERTY_ITEMS = "items";
  @jakarta.annotation.Nullable
  private List<HubItemDTO> items = new ArrayList<>();

  public static final String JSON_PROPERTY_SCHEDULED_AT = "scheduledAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime scheduledAt;

  public HubDeliveryQuoteRequest() { 
  }

  public HubDeliveryQuoteRequest deliveryType(@jakarta.annotation.Nonnull DeliveryTypeEnum deliveryType) {
    this.deliveryType = deliveryType;
    return this;
  }

  /**
   * Type of delivery
   * @return deliveryType
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DELIVERY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public DeliveryTypeEnum getDeliveryType() {
    return deliveryType;
  }


  @JsonProperty(JSON_PROPERTY_DELIVERY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDeliveryType(@jakarta.annotation.Nonnull DeliveryTypeEnum deliveryType) {
    this.deliveryType = deliveryType;
  }


  public HubDeliveryQuoteRequest pickup(@jakarta.annotation.Nonnull HubContactDTO pickup) {
    this.pickup = pickup;
    return this;
  }

  /**
   * Pickup contact and location
   * @return pickup
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PICKUP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public HubContactDTO getPickup() {
    return pickup;
  }


  @JsonProperty(JSON_PROPERTY_PICKUP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPickup(@jakarta.annotation.Nonnull HubContactDTO pickup) {
    this.pickup = pickup;
  }


  public HubDeliveryQuoteRequest dropoff(@jakarta.annotation.Nonnull HubContactDTO dropoff) {
    this.dropoff = dropoff;
    return this;
  }

  /**
   * Dropoff contact and location
   * @return dropoff
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DROPOFF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public HubContactDTO getDropoff() {
    return dropoff;
  }


  @JsonProperty(JSON_PROPERTY_DROPOFF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDropoff(@jakarta.annotation.Nonnull HubContactDTO dropoff) {
    this.dropoff = dropoff;
  }


  public HubDeliveryQuoteRequest items(@jakarta.annotation.Nullable List<HubItemDTO> items) {
    this.items = items;
    return this;
  }

  public HubDeliveryQuoteRequest addItemsItem(HubItemDTO itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

  /**
   * List of items for weight/size estimation
   * @return items
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<HubItemDTO> getItems() {
    return items;
  }


  @JsonProperty(JSON_PROPERTY_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setItems(@jakarta.annotation.Nullable List<HubItemDTO> items) {
    this.items = items;
  }


  public HubDeliveryQuoteRequest scheduledAt(@jakarta.annotation.Nullable OffsetDateTime scheduledAt) {
    this.scheduledAt = scheduledAt;
    return this;
  }

  /**
   * Scheduled pickup time (null for immediate)
   * @return scheduledAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCHEDULED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getScheduledAt() {
    return scheduledAt;
  }


  @JsonProperty(JSON_PROPERTY_SCHEDULED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScheduledAt(@jakarta.annotation.Nullable OffsetDateTime scheduledAt) {
    this.scheduledAt = scheduledAt;
  }


  /**
   * Return true if this HubDeliveryQuoteRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HubDeliveryQuoteRequest hubDeliveryQuoteRequest = (HubDeliveryQuoteRequest) o;
    return Objects.equals(this.deliveryType, hubDeliveryQuoteRequest.deliveryType) &&
        Objects.equals(this.pickup, hubDeliveryQuoteRequest.pickup) &&
        Objects.equals(this.dropoff, hubDeliveryQuoteRequest.dropoff) &&
        Objects.equals(this.items, hubDeliveryQuoteRequest.items) &&
        Objects.equals(this.scheduledAt, hubDeliveryQuoteRequest.scheduledAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deliveryType, pickup, dropoff, items, scheduledAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HubDeliveryQuoteRequest {\n");
    sb.append("    deliveryType: ").append(toIndentedString(deliveryType)).append("\n");
    sb.append("    pickup: ").append(toIndentedString(pickup)).append("\n");
    sb.append("    dropoff: ").append(toIndentedString(dropoff)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    scheduledAt: ").append(toIndentedString(scheduledAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `deliveryType` to the URL query string
    if (getDeliveryType() != null) {
      joiner.add(String.format("%sdeliveryType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeliveryType()))));
    }

    // add `pickup` to the URL query string
    if (getPickup() != null) {
      joiner.add(getPickup().toUrlQueryString(prefix + "pickup" + suffix));
    }

    // add `dropoff` to the URL query string
    if (getDropoff() != null) {
      joiner.add(getDropoff().toUrlQueryString(prefix + "dropoff" + suffix));
    }

    // add `items` to the URL query string
    if (getItems() != null) {
      for (int i = 0; i < getItems().size(); i++) {
        if (getItems().get(i) != null) {
          joiner.add(getItems().get(i).toUrlQueryString(String.format("%sitems%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `scheduledAt` to the URL query string
    if (getScheduledAt() != null) {
      joiner.add(String.format("%sscheduledAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getScheduledAt()))));
    }

    return joiner.toString();
  }
}

