/*
 * Service API
 * This API exposes endpoints.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zipper.delivery.hub.sdk.model.HubDeliveryLocationDTO;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zipper.delivery.hub.sdk.ApiClient;
/**
 * HubDeliverySearchDTO
 */
@JsonPropertyOrder({
  HubDeliverySearchDTO.JSON_PROPERTY_DELIVERY_ID,
  HubDeliverySearchDTO.JSON_PROPERTY_USER_ID,
  HubDeliverySearchDTO.JSON_PROPERTY_DELIVERY_TYPE,
  HubDeliverySearchDTO.JSON_PROPERTY_PROVIDER_TYPE,
  HubDeliverySearchDTO.JSON_PROPERTY_STATUS,
  HubDeliverySearchDTO.JSON_PROPERTY_HUB_TRACKING_NUMBER,
  HubDeliverySearchDTO.JSON_PROPERTY_HUB_ORDER_ID,
  HubDeliverySearchDTO.JSON_PROPERTY_EXTERNAL_ORDER_ID,
  HubDeliverySearchDTO.JSON_PROPERTY_PROVIDER_TRACKING_ID,
  HubDeliverySearchDTO.JSON_PROPERTY_PROVIDER_TRACKING_URL,
  HubDeliverySearchDTO.JSON_PROPERTY_SCHEDULED_PICKUP_TIME,
  HubDeliverySearchDTO.JSON_PROPERTY_ESTIMATED_ARRIVAL,
  HubDeliverySearchDTO.JSON_PROPERTY_CREATED_DATE,
  HubDeliverySearchDTO.JSON_PROPERTY_PICKUP_CONTACT_NAME,
  HubDeliverySearchDTO.JSON_PROPERTY_PICKUP_CONTACT_PHONE,
  HubDeliverySearchDTO.JSON_PROPERTY_PICKUP_LOCATION,
  HubDeliverySearchDTO.JSON_PROPERTY_DROPOFF_CONTACT_NAME,
  HubDeliverySearchDTO.JSON_PROPERTY_DROPOFF_CONTACT_PHONE,
  HubDeliverySearchDTO.JSON_PROPERTY_DROPOFF_LOCATION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class HubDeliverySearchDTO {
  public static final String JSON_PROPERTY_DELIVERY_ID = "deliveryId";
  @jakarta.annotation.Nullable
  private UUID deliveryId;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  @jakarta.annotation.Nullable
  private Long userId;

  /**
   * Gets or Sets deliveryType
   */
  public enum DeliveryTypeEnum {
    STORE_IMMEDIATE(String.valueOf("STORE_IMMEDIATE")),
    
    FOOD_IMMEDIATE(String.valueOf("FOOD_IMMEDIATE")),
    
    STORE_NEXT_DAY(String.valueOf("STORE_NEXT_DAY"));

    private String value;

    DeliveryTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DeliveryTypeEnum fromValue(String value) {
      for (DeliveryTypeEnum b : DeliveryTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DELIVERY_TYPE = "deliveryType";
  @jakarta.annotation.Nullable
  private DeliveryTypeEnum deliveryType;

  /**
   * Gets or Sets providerType
   */
  public enum ProviderTypeEnum {
    ZIPPERG(String.valueOf("ZIPPERG")),
    
    ZIPPERW(String.valueOf("ZIPPERW")),
    
    ZIPPERK(String.valueOf("ZIPPERK"));

    private String value;

    ProviderTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ProviderTypeEnum fromValue(String value) {
      for (ProviderTypeEnum b : ProviderTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PROVIDER_TYPE = "providerType";
  @jakarta.annotation.Nullable
  private ProviderTypeEnum providerType;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    CREATED(String.valueOf("CREATED")),
    
    ASSIGNED(String.valueOf("ASSIGNED")),
    
    READY_FOR_PICKUP(String.valueOf("READY_FOR_PICKUP")),
    
    PICKED_UP(String.valueOf("PICKED_UP")),
    
    IN_TRANSIT(String.valueOf("IN_TRANSIT")),
    
    DELIVERED(String.valueOf("DELIVERED")),
    
    CANCELLED(String.valueOf("CANCELLED")),
    
    FAILED(String.valueOf("FAILED")),
    
    REJECTED(String.valueOf("REJECTED"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private StatusEnum status;

  public static final String JSON_PROPERTY_HUB_TRACKING_NUMBER = "hubTrackingNumber";
  @jakarta.annotation.Nullable
  private String hubTrackingNumber;

  public static final String JSON_PROPERTY_HUB_ORDER_ID = "hubOrderId";
  @jakarta.annotation.Nullable
  private String hubOrderId;

  public static final String JSON_PROPERTY_EXTERNAL_ORDER_ID = "externalOrderId";
  @jakarta.annotation.Nullable
  private String externalOrderId;

  public static final String JSON_PROPERTY_PROVIDER_TRACKING_ID = "providerTrackingId";
  @jakarta.annotation.Nullable
  private String providerTrackingId;

  public static final String JSON_PROPERTY_PROVIDER_TRACKING_URL = "providerTrackingUrl";
  @jakarta.annotation.Nullable
  private String providerTrackingUrl;

  public static final String JSON_PROPERTY_SCHEDULED_PICKUP_TIME = "scheduledPickupTime";
  @jakarta.annotation.Nullable
  private OffsetDateTime scheduledPickupTime;

  public static final String JSON_PROPERTY_ESTIMATED_ARRIVAL = "estimatedArrival";
  @jakarta.annotation.Nullable
  private OffsetDateTime estimatedArrival;

  public static final String JSON_PROPERTY_CREATED_DATE = "createdDate";
  @jakarta.annotation.Nullable
  private OffsetDateTime createdDate;

  public static final String JSON_PROPERTY_PICKUP_CONTACT_NAME = "pickupContactName";
  @jakarta.annotation.Nullable
  private String pickupContactName;

  public static final String JSON_PROPERTY_PICKUP_CONTACT_PHONE = "pickupContactPhone";
  @jakarta.annotation.Nullable
  private String pickupContactPhone;

  public static final String JSON_PROPERTY_PICKUP_LOCATION = "pickupLocation";
  @jakarta.annotation.Nullable
  private HubDeliveryLocationDTO pickupLocation;

  public static final String JSON_PROPERTY_DROPOFF_CONTACT_NAME = "dropoffContactName";
  @jakarta.annotation.Nullable
  private String dropoffContactName;

  public static final String JSON_PROPERTY_DROPOFF_CONTACT_PHONE = "dropoffContactPhone";
  @jakarta.annotation.Nullable
  private String dropoffContactPhone;

  public static final String JSON_PROPERTY_DROPOFF_LOCATION = "dropoffLocation";
  @jakarta.annotation.Nullable
  private HubDeliveryLocationDTO dropoffLocation;

  public HubDeliverySearchDTO() { 
  }

  public HubDeliverySearchDTO deliveryId(@jakarta.annotation.Nullable UUID deliveryId) {
    this.deliveryId = deliveryId;
    return this;
  }

  /**
   * Get deliveryId
   * @return deliveryId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELIVERY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getDeliveryId() {
    return deliveryId;
  }


  @JsonProperty(JSON_PROPERTY_DELIVERY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeliveryId(@jakarta.annotation.Nullable UUID deliveryId) {
    this.deliveryId = deliveryId;
  }


  public HubDeliverySearchDTO userId(@jakarta.annotation.Nullable Long userId) {
    this.userId = userId;
    return this;
  }

  /**
   * Get userId
   * @return userId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserId(@jakarta.annotation.Nullable Long userId) {
    this.userId = userId;
  }


  public HubDeliverySearchDTO deliveryType(@jakarta.annotation.Nullable DeliveryTypeEnum deliveryType) {
    this.deliveryType = deliveryType;
    return this;
  }

  /**
   * Get deliveryType
   * @return deliveryType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELIVERY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public DeliveryTypeEnum getDeliveryType() {
    return deliveryType;
  }


  @JsonProperty(JSON_PROPERTY_DELIVERY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeliveryType(@jakarta.annotation.Nullable DeliveryTypeEnum deliveryType) {
    this.deliveryType = deliveryType;
  }


  public HubDeliverySearchDTO providerType(@jakarta.annotation.Nullable ProviderTypeEnum providerType) {
    this.providerType = providerType;
    return this;
  }

  /**
   * Get providerType
   * @return providerType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROVIDER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ProviderTypeEnum getProviderType() {
    return providerType;
  }


  @JsonProperty(JSON_PROPERTY_PROVIDER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProviderType(@jakarta.annotation.Nullable ProviderTypeEnum providerType) {
    this.providerType = providerType;
  }


  public HubDeliverySearchDTO status(@jakarta.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public HubDeliverySearchDTO hubTrackingNumber(@jakarta.annotation.Nullable String hubTrackingNumber) {
    this.hubTrackingNumber = hubTrackingNumber;
    return this;
  }

  /**
   * Get hubTrackingNumber
   * @return hubTrackingNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HUB_TRACKING_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHubTrackingNumber() {
    return hubTrackingNumber;
  }


  @JsonProperty(JSON_PROPERTY_HUB_TRACKING_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHubTrackingNumber(@jakarta.annotation.Nullable String hubTrackingNumber) {
    this.hubTrackingNumber = hubTrackingNumber;
  }


  public HubDeliverySearchDTO hubOrderId(@jakarta.annotation.Nullable String hubOrderId) {
    this.hubOrderId = hubOrderId;
    return this;
  }

  /**
   * Get hubOrderId
   * @return hubOrderId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HUB_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHubOrderId() {
    return hubOrderId;
  }


  @JsonProperty(JSON_PROPERTY_HUB_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHubOrderId(@jakarta.annotation.Nullable String hubOrderId) {
    this.hubOrderId = hubOrderId;
  }


  public HubDeliverySearchDTO externalOrderId(@jakarta.annotation.Nullable String externalOrderId) {
    this.externalOrderId = externalOrderId;
    return this;
  }

  /**
   * Get externalOrderId
   * @return externalOrderId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTERNAL_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getExternalOrderId() {
    return externalOrderId;
  }


  @JsonProperty(JSON_PROPERTY_EXTERNAL_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalOrderId(@jakarta.annotation.Nullable String externalOrderId) {
    this.externalOrderId = externalOrderId;
  }


  public HubDeliverySearchDTO providerTrackingId(@jakarta.annotation.Nullable String providerTrackingId) {
    this.providerTrackingId = providerTrackingId;
    return this;
  }

  /**
   * Get providerTrackingId
   * @return providerTrackingId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROVIDER_TRACKING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProviderTrackingId() {
    return providerTrackingId;
  }


  @JsonProperty(JSON_PROPERTY_PROVIDER_TRACKING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProviderTrackingId(@jakarta.annotation.Nullable String providerTrackingId) {
    this.providerTrackingId = providerTrackingId;
  }


  public HubDeliverySearchDTO providerTrackingUrl(@jakarta.annotation.Nullable String providerTrackingUrl) {
    this.providerTrackingUrl = providerTrackingUrl;
    return this;
  }

  /**
   * Get providerTrackingUrl
   * @return providerTrackingUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROVIDER_TRACKING_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProviderTrackingUrl() {
    return providerTrackingUrl;
  }


  @JsonProperty(JSON_PROPERTY_PROVIDER_TRACKING_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProviderTrackingUrl(@jakarta.annotation.Nullable String providerTrackingUrl) {
    this.providerTrackingUrl = providerTrackingUrl;
  }


  public HubDeliverySearchDTO scheduledPickupTime(@jakarta.annotation.Nullable OffsetDateTime scheduledPickupTime) {
    this.scheduledPickupTime = scheduledPickupTime;
    return this;
  }

  /**
   * Get scheduledPickupTime
   * @return scheduledPickupTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCHEDULED_PICKUP_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getScheduledPickupTime() {
    return scheduledPickupTime;
  }


  @JsonProperty(JSON_PROPERTY_SCHEDULED_PICKUP_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScheduledPickupTime(@jakarta.annotation.Nullable OffsetDateTime scheduledPickupTime) {
    this.scheduledPickupTime = scheduledPickupTime;
  }


  public HubDeliverySearchDTO estimatedArrival(@jakarta.annotation.Nullable OffsetDateTime estimatedArrival) {
    this.estimatedArrival = estimatedArrival;
    return this;
  }

  /**
   * Get estimatedArrival
   * @return estimatedArrival
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ESTIMATED_ARRIVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getEstimatedArrival() {
    return estimatedArrival;
  }


  @JsonProperty(JSON_PROPERTY_ESTIMATED_ARRIVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEstimatedArrival(@jakarta.annotation.Nullable OffsetDateTime estimatedArrival) {
    this.estimatedArrival = estimatedArrival;
  }


  public HubDeliverySearchDTO createdDate(@jakarta.annotation.Nullable OffsetDateTime createdDate) {
    this.createdDate = createdDate;
    return this;
  }

  /**
   * Get createdDate
   * @return createdDate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreatedDate() {
    return createdDate;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedDate(@jakarta.annotation.Nullable OffsetDateTime createdDate) {
    this.createdDate = createdDate;
  }


  public HubDeliverySearchDTO pickupContactName(@jakarta.annotation.Nullable String pickupContactName) {
    this.pickupContactName = pickupContactName;
    return this;
  }

  /**
   * Get pickupContactName
   * @return pickupContactName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PICKUP_CONTACT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPickupContactName() {
    return pickupContactName;
  }


  @JsonProperty(JSON_PROPERTY_PICKUP_CONTACT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPickupContactName(@jakarta.annotation.Nullable String pickupContactName) {
    this.pickupContactName = pickupContactName;
  }


  public HubDeliverySearchDTO pickupContactPhone(@jakarta.annotation.Nullable String pickupContactPhone) {
    this.pickupContactPhone = pickupContactPhone;
    return this;
  }

  /**
   * Get pickupContactPhone
   * @return pickupContactPhone
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PICKUP_CONTACT_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPickupContactPhone() {
    return pickupContactPhone;
  }


  @JsonProperty(JSON_PROPERTY_PICKUP_CONTACT_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPickupContactPhone(@jakarta.annotation.Nullable String pickupContactPhone) {
    this.pickupContactPhone = pickupContactPhone;
  }


  public HubDeliverySearchDTO pickupLocation(@jakarta.annotation.Nullable HubDeliveryLocationDTO pickupLocation) {
    this.pickupLocation = pickupLocation;
    return this;
  }

  /**
   * Get pickupLocation
   * @return pickupLocation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PICKUP_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public HubDeliveryLocationDTO getPickupLocation() {
    return pickupLocation;
  }


  @JsonProperty(JSON_PROPERTY_PICKUP_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPickupLocation(@jakarta.annotation.Nullable HubDeliveryLocationDTO pickupLocation) {
    this.pickupLocation = pickupLocation;
  }


  public HubDeliverySearchDTO dropoffContactName(@jakarta.annotation.Nullable String dropoffContactName) {
    this.dropoffContactName = dropoffContactName;
    return this;
  }

  /**
   * Get dropoffContactName
   * @return dropoffContactName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DROPOFF_CONTACT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDropoffContactName() {
    return dropoffContactName;
  }


  @JsonProperty(JSON_PROPERTY_DROPOFF_CONTACT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDropoffContactName(@jakarta.annotation.Nullable String dropoffContactName) {
    this.dropoffContactName = dropoffContactName;
  }


  public HubDeliverySearchDTO dropoffContactPhone(@jakarta.annotation.Nullable String dropoffContactPhone) {
    this.dropoffContactPhone = dropoffContactPhone;
    return this;
  }

  /**
   * Get dropoffContactPhone
   * @return dropoffContactPhone
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DROPOFF_CONTACT_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDropoffContactPhone() {
    return dropoffContactPhone;
  }


  @JsonProperty(JSON_PROPERTY_DROPOFF_CONTACT_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDropoffContactPhone(@jakarta.annotation.Nullable String dropoffContactPhone) {
    this.dropoffContactPhone = dropoffContactPhone;
  }


  public HubDeliverySearchDTO dropoffLocation(@jakarta.annotation.Nullable HubDeliveryLocationDTO dropoffLocation) {
    this.dropoffLocation = dropoffLocation;
    return this;
  }

  /**
   * Get dropoffLocation
   * @return dropoffLocation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DROPOFF_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public HubDeliveryLocationDTO getDropoffLocation() {
    return dropoffLocation;
  }


  @JsonProperty(JSON_PROPERTY_DROPOFF_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDropoffLocation(@jakarta.annotation.Nullable HubDeliveryLocationDTO dropoffLocation) {
    this.dropoffLocation = dropoffLocation;
  }


  /**
   * Return true if this HubDeliverySearchDTO object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HubDeliverySearchDTO hubDeliverySearchDTO = (HubDeliverySearchDTO) o;
    return Objects.equals(this.deliveryId, hubDeliverySearchDTO.deliveryId) &&
        Objects.equals(this.userId, hubDeliverySearchDTO.userId) &&
        Objects.equals(this.deliveryType, hubDeliverySearchDTO.deliveryType) &&
        Objects.equals(this.providerType, hubDeliverySearchDTO.providerType) &&
        Objects.equals(this.status, hubDeliverySearchDTO.status) &&
        Objects.equals(this.hubTrackingNumber, hubDeliverySearchDTO.hubTrackingNumber) &&
        Objects.equals(this.hubOrderId, hubDeliverySearchDTO.hubOrderId) &&
        Objects.equals(this.externalOrderId, hubDeliverySearchDTO.externalOrderId) &&
        Objects.equals(this.providerTrackingId, hubDeliverySearchDTO.providerTrackingId) &&
        Objects.equals(this.providerTrackingUrl, hubDeliverySearchDTO.providerTrackingUrl) &&
        Objects.equals(this.scheduledPickupTime, hubDeliverySearchDTO.scheduledPickupTime) &&
        Objects.equals(this.estimatedArrival, hubDeliverySearchDTO.estimatedArrival) &&
        Objects.equals(this.createdDate, hubDeliverySearchDTO.createdDate) &&
        Objects.equals(this.pickupContactName, hubDeliverySearchDTO.pickupContactName) &&
        Objects.equals(this.pickupContactPhone, hubDeliverySearchDTO.pickupContactPhone) &&
        Objects.equals(this.pickupLocation, hubDeliverySearchDTO.pickupLocation) &&
        Objects.equals(this.dropoffContactName, hubDeliverySearchDTO.dropoffContactName) &&
        Objects.equals(this.dropoffContactPhone, hubDeliverySearchDTO.dropoffContactPhone) &&
        Objects.equals(this.dropoffLocation, hubDeliverySearchDTO.dropoffLocation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deliveryId, userId, deliveryType, providerType, status, hubTrackingNumber, hubOrderId, externalOrderId, providerTrackingId, providerTrackingUrl, scheduledPickupTime, estimatedArrival, createdDate, pickupContactName, pickupContactPhone, pickupLocation, dropoffContactName, dropoffContactPhone, dropoffLocation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HubDeliverySearchDTO {\n");
    sb.append("    deliveryId: ").append(toIndentedString(deliveryId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    deliveryType: ").append(toIndentedString(deliveryType)).append("\n");
    sb.append("    providerType: ").append(toIndentedString(providerType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    hubTrackingNumber: ").append(toIndentedString(hubTrackingNumber)).append("\n");
    sb.append("    hubOrderId: ").append(toIndentedString(hubOrderId)).append("\n");
    sb.append("    externalOrderId: ").append(toIndentedString(externalOrderId)).append("\n");
    sb.append("    providerTrackingId: ").append(toIndentedString(providerTrackingId)).append("\n");
    sb.append("    providerTrackingUrl: ").append(toIndentedString(providerTrackingUrl)).append("\n");
    sb.append("    scheduledPickupTime: ").append(toIndentedString(scheduledPickupTime)).append("\n");
    sb.append("    estimatedArrival: ").append(toIndentedString(estimatedArrival)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    pickupContactName: ").append(toIndentedString(pickupContactName)).append("\n");
    sb.append("    pickupContactPhone: ").append(toIndentedString(pickupContactPhone)).append("\n");
    sb.append("    pickupLocation: ").append(toIndentedString(pickupLocation)).append("\n");
    sb.append("    dropoffContactName: ").append(toIndentedString(dropoffContactName)).append("\n");
    sb.append("    dropoffContactPhone: ").append(toIndentedString(dropoffContactPhone)).append("\n");
    sb.append("    dropoffLocation: ").append(toIndentedString(dropoffLocation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `deliveryId` to the URL query string
    if (getDeliveryId() != null) {
      joiner.add(String.format("%sdeliveryId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeliveryId()))));
    }

    // add `userId` to the URL query string
    if (getUserId() != null) {
      joiner.add(String.format("%suserId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUserId()))));
    }

    // add `deliveryType` to the URL query string
    if (getDeliveryType() != null) {
      joiner.add(String.format("%sdeliveryType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeliveryType()))));
    }

    // add `providerType` to the URL query string
    if (getProviderType() != null) {
      joiner.add(String.format("%sproviderType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProviderType()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format("%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `hubTrackingNumber` to the URL query string
    if (getHubTrackingNumber() != null) {
      joiner.add(String.format("%shubTrackingNumber%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHubTrackingNumber()))));
    }

    // add `hubOrderId` to the URL query string
    if (getHubOrderId() != null) {
      joiner.add(String.format("%shubOrderId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHubOrderId()))));
    }

    // add `externalOrderId` to the URL query string
    if (getExternalOrderId() != null) {
      joiner.add(String.format("%sexternalOrderId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExternalOrderId()))));
    }

    // add `providerTrackingId` to the URL query string
    if (getProviderTrackingId() != null) {
      joiner.add(String.format("%sproviderTrackingId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProviderTrackingId()))));
    }

    // add `providerTrackingUrl` to the URL query string
    if (getProviderTrackingUrl() != null) {
      joiner.add(String.format("%sproviderTrackingUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProviderTrackingUrl()))));
    }

    // add `scheduledPickupTime` to the URL query string
    if (getScheduledPickupTime() != null) {
      joiner.add(String.format("%sscheduledPickupTime%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getScheduledPickupTime()))));
    }

    // add `estimatedArrival` to the URL query string
    if (getEstimatedArrival() != null) {
      joiner.add(String.format("%sestimatedArrival%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEstimatedArrival()))));
    }

    // add `createdDate` to the URL query string
    if (getCreatedDate() != null) {
      joiner.add(String.format("%screatedDate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedDate()))));
    }

    // add `pickupContactName` to the URL query string
    if (getPickupContactName() != null) {
      joiner.add(String.format("%spickupContactName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPickupContactName()))));
    }

    // add `pickupContactPhone` to the URL query string
    if (getPickupContactPhone() != null) {
      joiner.add(String.format("%spickupContactPhone%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPickupContactPhone()))));
    }

    // add `pickupLocation` to the URL query string
    if (getPickupLocation() != null) {
      joiner.add(getPickupLocation().toUrlQueryString(prefix + "pickupLocation" + suffix));
    }

    // add `dropoffContactName` to the URL query string
    if (getDropoffContactName() != null) {
      joiner.add(String.format("%sdropoffContactName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDropoffContactName()))));
    }

    // add `dropoffContactPhone` to the URL query string
    if (getDropoffContactPhone() != null) {
      joiner.add(String.format("%sdropoffContactPhone%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDropoffContactPhone()))));
    }

    // add `dropoffLocation` to the URL query string
    if (getDropoffLocation() != null) {
      joiner.add(getDropoffLocation().toUrlQueryString(prefix + "dropoffLocation" + suffix));
    }

    return joiner.toString();
  }
}

