/*
 * Service API
 * This API exposes endpoints.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zipper.delivery.hub.sdk.ApiClient;
/**
 * Label metadata and asset URLs for a delivery
 */
@JsonPropertyOrder({
  HubDeliveryLabelResponse.JSON_PROPERTY_BARCODE,
  HubDeliveryLabelResponse.JSON_PROPERTY_BARCODE_IMAGE,
  HubDeliveryLabelResponse.JSON_PROPERTY_QR_CODE,
  HubDeliveryLabelResponse.JSON_PROPERTY_LABEL_PDF
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class HubDeliveryLabelResponse {
  public static final String JSON_PROPERTY_BARCODE = "barcode";
  @jakarta.annotation.Nullable
  private String barcode;

  public static final String JSON_PROPERTY_BARCODE_IMAGE = "barcodeImage";
  @jakarta.annotation.Nullable
  private String barcodeImage;

  public static final String JSON_PROPERTY_QR_CODE = "qrCode";
  @jakarta.annotation.Nullable
  private String qrCode;

  public static final String JSON_PROPERTY_LABEL_PDF = "labelPdf";
  @jakarta.annotation.Nullable
  private String labelPdf;

  public HubDeliveryLabelResponse() { 
  }

  public HubDeliveryLabelResponse barcode(@jakarta.annotation.Nullable String barcode) {
    this.barcode = barcode;
    return this;
  }

  /**
   * Barcode value (tracking number or barcode)
   * @return barcode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BARCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBarcode() {
    return barcode;
  }


  @JsonProperty(JSON_PROPERTY_BARCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBarcode(@jakarta.annotation.Nullable String barcode) {
    this.barcode = barcode;
  }


  public HubDeliveryLabelResponse barcodeImage(@jakarta.annotation.Nullable String barcodeImage) {
    this.barcodeImage = barcodeImage;
    return this;
  }

  /**
   * URL to the barcode image (PNG)
   * @return barcodeImage
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BARCODE_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBarcodeImage() {
    return barcodeImage;
  }


  @JsonProperty(JSON_PROPERTY_BARCODE_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBarcodeImage(@jakarta.annotation.Nullable String barcodeImage) {
    this.barcodeImage = barcodeImage;
  }


  public HubDeliveryLabelResponse qrCode(@jakarta.annotation.Nullable String qrCode) {
    this.qrCode = qrCode;
    return this;
  }

  /**
   * URL to the QR code image (PNG)
   * @return qrCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getQrCode() {
    return qrCode;
  }


  @JsonProperty(JSON_PROPERTY_QR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQrCode(@jakarta.annotation.Nullable String qrCode) {
    this.qrCode = qrCode;
  }


  public HubDeliveryLabelResponse labelPdf(@jakarta.annotation.Nullable String labelPdf) {
    this.labelPdf = labelPdf;
    return this;
  }

  /**
   * URL to the label PDF
   * @return labelPdf
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LABEL_PDF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLabelPdf() {
    return labelPdf;
  }


  @JsonProperty(JSON_PROPERTY_LABEL_PDF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLabelPdf(@jakarta.annotation.Nullable String labelPdf) {
    this.labelPdf = labelPdf;
  }


  /**
   * Return true if this HubDeliveryLabelResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HubDeliveryLabelResponse hubDeliveryLabelResponse = (HubDeliveryLabelResponse) o;
    return Objects.equals(this.barcode, hubDeliveryLabelResponse.barcode) &&
        Objects.equals(this.barcodeImage, hubDeliveryLabelResponse.barcodeImage) &&
        Objects.equals(this.qrCode, hubDeliveryLabelResponse.qrCode) &&
        Objects.equals(this.labelPdf, hubDeliveryLabelResponse.labelPdf);
  }

  @Override
  public int hashCode() {
    return Objects.hash(barcode, barcodeImage, qrCode, labelPdf);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HubDeliveryLabelResponse {\n");
    sb.append("    barcode: ").append(toIndentedString(barcode)).append("\n");
    sb.append("    barcodeImage: ").append(toIndentedString(barcodeImage)).append("\n");
    sb.append("    qrCode: ").append(toIndentedString(qrCode)).append("\n");
    sb.append("    labelPdf: ").append(toIndentedString(labelPdf)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `barcode` to the URL query string
    if (getBarcode() != null) {
      joiner.add(String.format("%sbarcode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBarcode()))));
    }

    // add `barcodeImage` to the URL query string
    if (getBarcodeImage() != null) {
      joiner.add(String.format("%sbarcodeImage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBarcodeImage()))));
    }

    // add `qrCode` to the URL query string
    if (getQrCode() != null) {
      joiner.add(String.format("%sqrCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQrCode()))));
    }

    // add `labelPdf` to the URL query string
    if (getLabelPdf() != null) {
      joiner.add(String.format("%slabelPdf%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLabelPdf()))));
    }

    return joiner.toString();
  }
}

