/*
 * Service API
 * This API exposes endpoints.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zipper.delivery.hub.sdk.ApiClient;
/**
 * HubDeliveryLocationDTO
 */
@JsonPropertyOrder({
  HubDeliveryLocationDTO.JSON_PROPERTY_LAT,
  HubDeliveryLocationDTO.JSON_PROPERTY_LNG,
  HubDeliveryLocationDTO.JSON_PROPERTY_FULL_ADDRESS,
  HubDeliveryLocationDTO.JSON_PROPERTY_CITY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class HubDeliveryLocationDTO {
  public static final String JSON_PROPERTY_LAT = "lat";
  @jakarta.annotation.Nullable
  private Double lat;

  public static final String JSON_PROPERTY_LNG = "lng";
  @jakarta.annotation.Nullable
  private Double lng;

  public static final String JSON_PROPERTY_FULL_ADDRESS = "fullAddress";
  @jakarta.annotation.Nullable
  private String fullAddress;

  public static final String JSON_PROPERTY_CITY = "city";
  @jakarta.annotation.Nullable
  private String city;

  public HubDeliveryLocationDTO() { 
  }

  public HubDeliveryLocationDTO lat(@jakarta.annotation.Nullable Double lat) {
    this.lat = lat;
    return this;
  }

  /**
   * Get lat
   * @return lat
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getLat() {
    return lat;
  }


  @JsonProperty(JSON_PROPERTY_LAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLat(@jakarta.annotation.Nullable Double lat) {
    this.lat = lat;
  }


  public HubDeliveryLocationDTO lng(@jakarta.annotation.Nullable Double lng) {
    this.lng = lng;
    return this;
  }

  /**
   * Get lng
   * @return lng
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LNG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getLng() {
    return lng;
  }


  @JsonProperty(JSON_PROPERTY_LNG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLng(@jakarta.annotation.Nullable Double lng) {
    this.lng = lng;
  }


  public HubDeliveryLocationDTO fullAddress(@jakarta.annotation.Nullable String fullAddress) {
    this.fullAddress = fullAddress;
    return this;
  }

  /**
   * Get fullAddress
   * @return fullAddress
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FULL_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFullAddress() {
    return fullAddress;
  }


  @JsonProperty(JSON_PROPERTY_FULL_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFullAddress(@jakarta.annotation.Nullable String fullAddress) {
    this.fullAddress = fullAddress;
  }


  public HubDeliveryLocationDTO city(@jakarta.annotation.Nullable String city) {
    this.city = city;
    return this;
  }

  /**
   * Get city
   * @return city
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCity() {
    return city;
  }


  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCity(@jakarta.annotation.Nullable String city) {
    this.city = city;
  }


  /**
   * Return true if this HubDeliveryLocationDTO object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HubDeliveryLocationDTO hubDeliveryLocationDTO = (HubDeliveryLocationDTO) o;
    return Objects.equals(this.lat, hubDeliveryLocationDTO.lat) &&
        Objects.equals(this.lng, hubDeliveryLocationDTO.lng) &&
        Objects.equals(this.fullAddress, hubDeliveryLocationDTO.fullAddress) &&
        Objects.equals(this.city, hubDeliveryLocationDTO.city);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lat, lng, fullAddress, city);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HubDeliveryLocationDTO {\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    lng: ").append(toIndentedString(lng)).append("\n");
    sb.append("    fullAddress: ").append(toIndentedString(fullAddress)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `lat` to the URL query string
    if (getLat() != null) {
      joiner.add(String.format("%slat%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLat()))));
    }

    // add `lng` to the URL query string
    if (getLng() != null) {
      joiner.add(String.format("%slng%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLng()))));
    }

    // add `fullAddress` to the URL query string
    if (getFullAddress() != null) {
      joiner.add(String.format("%sfullAddress%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFullAddress()))));
    }

    // add `city` to the URL query string
    if (getCity() != null) {
      joiner.add(String.format("%scity%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCity()))));
    }

    return joiner.toString();
  }
}

