/*
 * Service API
 * This API exposes endpoints.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zipper.delivery.hub.sdk.ApiClient;
/**
 * Handshake PIN information for a delivery
 */
@JsonPropertyOrder({
  HubHandshakeDeliveryResponse.JSON_PROPERTY_REQUIRED,
  HubHandshakeDeliveryResponse.JSON_PROPERTY_PIN_CODE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class HubHandshakeDeliveryResponse {
  public static final String JSON_PROPERTY_REQUIRED = "required";
  @jakarta.annotation.Nullable
  private Boolean required;

  public static final String JSON_PROPERTY_PIN_CODE = "pinCode";
  @jakarta.annotation.Nullable
  private Integer pinCode;

  public HubHandshakeDeliveryResponse() { 
  }

  public HubHandshakeDeliveryResponse required(@jakarta.annotation.Nullable Boolean required) {
    this.required = required;
    return this;
  }

  /**
   * Whether a PIN handshake is required for this delivery
   * @return required
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getRequired() {
    return required;
  }


  @JsonProperty(JSON_PROPERTY_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequired(@jakarta.annotation.Nullable Boolean required) {
    this.required = required;
  }


  public HubHandshakeDeliveryResponse pinCode(@jakarta.annotation.Nullable Integer pinCode) {
    this.pinCode = pinCode;
    return this;
  }

  /**
   * PIN code for the handshake
   * @return pinCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PIN_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getPinCode() {
    return pinCode;
  }


  @JsonProperty(JSON_PROPERTY_PIN_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPinCode(@jakarta.annotation.Nullable Integer pinCode) {
    this.pinCode = pinCode;
  }


  /**
   * Return true if this HubHandshakeDeliveryResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HubHandshakeDeliveryResponse hubHandshakeDeliveryResponse = (HubHandshakeDeliveryResponse) o;
    return Objects.equals(this.required, hubHandshakeDeliveryResponse.required) &&
        Objects.equals(this.pinCode, hubHandshakeDeliveryResponse.pinCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(required, pinCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HubHandshakeDeliveryResponse {\n");
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("    pinCode: ").append(toIndentedString(pinCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `required` to the URL query string
    if (getRequired() != null) {
      joiner.add(String.format("%srequired%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRequired()))));
    }

    // add `pinCode` to the URL query string
    if (getPinCode() != null) {
      joiner.add(String.format("%spinCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPinCode()))));
    }

    return joiner.toString();
  }
}

