/*
 * Service API
 * This API exposes endpoints.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zipper.delivery.hub.sdk.ApiClient;
/**
 * A single status change event in the delivery lifecycle
 */
@JsonPropertyOrder({
  HubStatusEventDTO.JSON_PROPERTY_STATUS,
  HubStatusEventDTO.JSON_PROPERTY_OCCURRED_AT,
  HubStatusEventDTO.JSON_PROPERTY_DESCRIPTION,
  HubStatusEventDTO.JSON_PROPERTY_PROOF_OF_DELIVERY_URL
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class HubStatusEventDTO {
  /**
   * Delivery status at this event
   */
  public enum StatusEnum {
    CREATED(String.valueOf("CREATED")),
    
    ASSIGNED(String.valueOf("ASSIGNED")),
    
    READY_FOR_PICKUP(String.valueOf("READY_FOR_PICKUP")),
    
    PICKED_UP(String.valueOf("PICKED_UP")),
    
    IN_TRANSIT(String.valueOf("IN_TRANSIT")),
    
    DELIVERED(String.valueOf("DELIVERED")),
    
    CANCELLED(String.valueOf("CANCELLED")),
    
    FAILED(String.valueOf("FAILED")),
    
    REJECTED(String.valueOf("REJECTED"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private StatusEnum status;

  public static final String JSON_PROPERTY_OCCURRED_AT = "occurredAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime occurredAt;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_PROOF_OF_DELIVERY_URL = "proofOfDeliveryUrl";
  @jakarta.annotation.Nullable
  private String proofOfDeliveryUrl;

  public HubStatusEventDTO() { 
  }

  public HubStatusEventDTO status(@jakarta.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Delivery status at this event
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public HubStatusEventDTO occurredAt(@jakarta.annotation.Nullable OffsetDateTime occurredAt) {
    this.occurredAt = occurredAt;
    return this;
  }

  /**
   * When this status change occurred
   * @return occurredAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OCCURRED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getOccurredAt() {
    return occurredAt;
  }


  @JsonProperty(JSON_PROPERTY_OCCURRED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOccurredAt(@jakarta.annotation.Nullable OffsetDateTime occurredAt) {
    this.occurredAt = occurredAt;
  }


  public HubStatusEventDTO description(@jakarta.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Human-readable description of the event
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }


  public HubStatusEventDTO proofOfDeliveryUrl(@jakarta.annotation.Nullable String proofOfDeliveryUrl) {
    this.proofOfDeliveryUrl = proofOfDeliveryUrl;
    return this;
  }

  /**
   * URL to proof-of-delivery image (only for DELIVERED status)
   * @return proofOfDeliveryUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROOF_OF_DELIVERY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProofOfDeliveryUrl() {
    return proofOfDeliveryUrl;
  }


  @JsonProperty(JSON_PROPERTY_PROOF_OF_DELIVERY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProofOfDeliveryUrl(@jakarta.annotation.Nullable String proofOfDeliveryUrl) {
    this.proofOfDeliveryUrl = proofOfDeliveryUrl;
  }


  /**
   * Return true if this HubStatusEventDTO object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HubStatusEventDTO hubStatusEventDTO = (HubStatusEventDTO) o;
    return Objects.equals(this.status, hubStatusEventDTO.status) &&
        Objects.equals(this.occurredAt, hubStatusEventDTO.occurredAt) &&
        Objects.equals(this.description, hubStatusEventDTO.description) &&
        Objects.equals(this.proofOfDeliveryUrl, hubStatusEventDTO.proofOfDeliveryUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, occurredAt, description, proofOfDeliveryUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HubStatusEventDTO {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    occurredAt: ").append(toIndentedString(occurredAt)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    proofOfDeliveryUrl: ").append(toIndentedString(proofOfDeliveryUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format("%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `occurredAt` to the URL query string
    if (getOccurredAt() != null) {
      joiner.add(String.format("%soccurredAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOccurredAt()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format("%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `proofOfDeliveryUrl` to the URL query string
    if (getProofOfDeliveryUrl() != null) {
      joiner.add(String.format("%sproofOfDeliveryUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProofOfDeliveryUrl()))));
    }

    return joiner.toString();
  }
}

