/*
 * Service API
 * This API exposes endpoints.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zipper.delivery.hub.sdk.model.AddressDTO;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zipper.delivery.hub.sdk.ApiClient;
/**
 * Geographic location with structured address
 */
@JsonPropertyOrder({
  LocationDTO.JSON_PROPERTY_LAT,
  LocationDTO.JSON_PROPERTY_LNG,
  LocationDTO.JSON_PROPERTY_ADDRESS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class LocationDTO {
  public static final String JSON_PROPERTY_LAT = "lat";
  @jakarta.annotation.Nonnull
  private Double lat;

  public static final String JSON_PROPERTY_LNG = "lng";
  @jakarta.annotation.Nonnull
  private Double lng;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  @jakarta.annotation.Nonnull
  private AddressDTO address;

  public LocationDTO() { 
  }

  public LocationDTO lat(@jakarta.annotation.Nonnull Double lat) {
    this.lat = lat;
    return this;
  }

  /**
   * Latitude coordinate
   * @return lat
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LAT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Double getLat() {
    return lat;
  }


  @JsonProperty(JSON_PROPERTY_LAT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLat(@jakarta.annotation.Nonnull Double lat) {
    this.lat = lat;
  }


  public LocationDTO lng(@jakarta.annotation.Nonnull Double lng) {
    this.lng = lng;
    return this;
  }

  /**
   * Longitude coordinate
   * @return lng
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LNG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Double getLng() {
    return lng;
  }


  @JsonProperty(JSON_PROPERTY_LNG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLng(@jakarta.annotation.Nonnull Double lng) {
    this.lng = lng;
  }


  public LocationDTO address(@jakarta.annotation.Nonnull AddressDTO address) {
    this.address = address;
    return this;
  }

  /**
   * Structured address details
   * @return address
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public AddressDTO getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAddress(@jakarta.annotation.Nonnull AddressDTO address) {
    this.address = address;
  }


  /**
   * Return true if this LocationDTO object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocationDTO locationDTO = (LocationDTO) o;
    return Objects.equals(this.lat, locationDTO.lat) &&
        Objects.equals(this.lng, locationDTO.lng) &&
        Objects.equals(this.address, locationDTO.address);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lat, lng, address);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocationDTO {\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    lng: ").append(toIndentedString(lng)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `lat` to the URL query string
    if (getLat() != null) {
      joiner.add(String.format("%slat%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLat()))));
    }

    // add `lng` to the URL query string
    if (getLng() != null) {
      joiner.add(String.format("%slng%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLng()))));
    }

    // add `address` to the URL query string
    if (getAddress() != null) {
      joiner.add(getAddress().toUrlQueryString(prefix + "address" + suffix));
    }

    return joiner.toString();
  }
}

