/*
 * Service API
 * This API exposes endpoints.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zipper.delivery.hub.sdk.ApiClient;
/**
 * Pagination parameters for controlling result set size and page selection
 */
@JsonPropertyOrder({
  Pagination.JSON_PROPERTY_ITEMS_PER_PAGE,
  Pagination.JSON_PROPERTY_PAGE_NUMBER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class Pagination {
  public static final String JSON_PROPERTY_ITEMS_PER_PAGE = "itemsPerPage";
  @jakarta.annotation.Nullable
  private Integer itemsPerPage = 50;

  public static final String JSON_PROPERTY_PAGE_NUMBER = "pageNumber";
  @jakarta.annotation.Nullable
  private Integer pageNumber = 1;

  public Pagination() { 
  }

  public Pagination itemsPerPage(@jakarta.annotation.Nullable Integer itemsPerPage) {
    this.itemsPerPage = itemsPerPage;
    return this;
  }

  /**
   * Number of items per page. Defaults to 50 if not specified.
   * minimum: 1
   * maximum: 1000
   * @return itemsPerPage
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ITEMS_PER_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getItemsPerPage() {
    return itemsPerPage;
  }


  @JsonProperty(JSON_PROPERTY_ITEMS_PER_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setItemsPerPage(@jakarta.annotation.Nullable Integer itemsPerPage) {
    this.itemsPerPage = itemsPerPage;
  }


  public Pagination pageNumber(@jakarta.annotation.Nullable Integer pageNumber) {
    this.pageNumber = pageNumber;
    return this;
  }

  /**
   * Page number (1-based indexing). Defaults to 1 if not specified.
   * minimum: 1
   * @return pageNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAGE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getPageNumber() {
    return pageNumber;
  }


  @JsonProperty(JSON_PROPERTY_PAGE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPageNumber(@jakarta.annotation.Nullable Integer pageNumber) {
    this.pageNumber = pageNumber;
  }


  /**
   * Return true if this Pagination object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Pagination pagination = (Pagination) o;
    return Objects.equals(this.itemsPerPage, pagination.itemsPerPage) &&
        Objects.equals(this.pageNumber, pagination.pageNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemsPerPage, pageNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Pagination {\n");
    sb.append("    itemsPerPage: ").append(toIndentedString(itemsPerPage)).append("\n");
    sb.append("    pageNumber: ").append(toIndentedString(pageNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `itemsPerPage` to the URL query string
    if (getItemsPerPage() != null) {
      joiner.add(String.format("%sitemsPerPage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getItemsPerPage()))));
    }

    // add `pageNumber` to the URL query string
    if (getPageNumber() != null) {
      joiner.add(String.format("%spageNumber%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPageNumber()))));
    }

    return joiner.toString();
  }
}

