/*
 * Service API
 * This API exposes endpoints.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zipper.delivery.hub.sdk.model.Filter;
import com.zipper.delivery.hub.sdk.model.Pagination;
import com.zipper.delivery.hub.sdk.model.SortField;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zipper.delivery.hub.sdk.ApiClient;
/**
 * Advanced search request for deliveries with filtering, sorting, and pagination capabilities. **Query Fields** (full-text search): &#x60;providerTrackingId&#x60;, &#x60;externalOrderId&#x60; **Available Filter/Sort Fields:** - &#x60;status&#x60; (HubDeliveryStatus, sortable) - CREATED, ASSIGNED, PICKED_UP, IN_TRANSIT, DELIVERED, CANCELLED, FAILED - &#x60;deliveryType&#x60; (DeliveryType, sortable) - &#x60;providerType&#x60; (DeliveryProviderType, sortable) - &#x60;createdDate&#x60; (Instant, sortable) - &#x60;userId&#x60; (Long, sortable) - Auto-filtered for non-admin users 
 */
@JsonPropertyOrder({
  SearchDeliveriesRequest.JSON_PROPERTY_QUERY,
  SearchDeliveriesRequest.JSON_PROPERTY_FILTERS,
  SearchDeliveriesRequest.JSON_PROPERTY_SORT,
  SearchDeliveriesRequest.JSON_PROPERTY_PAGINATION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class SearchDeliveriesRequest {
  public static final String JSON_PROPERTY_QUERY = "query";
  @jakarta.annotation.Nullable
  private String query;

  public static final String JSON_PROPERTY_FILTERS = "filters";
  @jakarta.annotation.Nullable
  private Map<String, List<Filter>> filters = new HashMap<>();

  public static final String JSON_PROPERTY_SORT = "sort";
  @jakarta.annotation.Nullable
  private List<SortField> sort = new ArrayList<>();

  public static final String JSON_PROPERTY_PAGINATION = "pagination";
  @jakarta.annotation.Nullable
  private Pagination pagination;

  public SearchDeliveriesRequest() { 
  }

  public SearchDeliveriesRequest query(@jakarta.annotation.Nullable String query) {
    this.query = query;
    return this;
  }

  /**
   * Full-text search query string. Matches against predefined query fields using case-insensitive LIKE.
   * @return query
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getQuery() {
    return query;
  }


  @JsonProperty(JSON_PROPERTY_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuery(@jakarta.annotation.Nullable String query) {
    this.query = query;
  }


  public SearchDeliveriesRequest filters(@jakarta.annotation.Nullable Map<String, List<Filter>> filters) {
    this.filters = filters;
    return this;
  }

  public SearchDeliveriesRequest putFiltersItem(String key, List<Filter> filtersItem) {
    if (this.filters == null) {
      this.filters = new HashMap<>();
    }
    this.filters.put(key, filtersItem);
    return this;
  }

  /**
   * Filter groups with AND/OR logic. Each group contains a list of filter criteria that are combined using the specified operator.
   * @return filters
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILTERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, List<Filter>> getFilters() {
    return filters;
  }


  @JsonProperty(JSON_PROPERTY_FILTERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilters(@jakarta.annotation.Nullable Map<String, List<Filter>> filters) {
    this.filters = filters;
  }


  public SearchDeliveriesRequest sort(@jakarta.annotation.Nullable List<SortField> sort) {
    this.sort = sort;
    return this;
  }

  public SearchDeliveriesRequest addSortItem(SortField sortItem) {
    if (this.sort == null) {
      this.sort = new ArrayList<>();
    }
    this.sort.add(sortItem);
    return this;
  }

  /**
   * Sort criteria applied in order. Only sortable fields are accepted.
   * @return sort
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<SortField> getSort() {
    return sort;
  }


  @JsonProperty(JSON_PROPERTY_SORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSort(@jakarta.annotation.Nullable List<SortField> sort) {
    this.sort = sort;
  }


  public SearchDeliveriesRequest pagination(@jakarta.annotation.Nullable Pagination pagination) {
    this.pagination = pagination;
    return this;
  }

  /**
   * Pagination parameters. Page numbers are 1-based.
   * @return pagination
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAGINATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Pagination getPagination() {
    return pagination;
  }


  @JsonProperty(JSON_PROPERTY_PAGINATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPagination(@jakarta.annotation.Nullable Pagination pagination) {
    this.pagination = pagination;
  }


  /**
   * Return true if this SearchDeliveriesRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchDeliveriesRequest searchDeliveriesRequest = (SearchDeliveriesRequest) o;
    return Objects.equals(this.query, searchDeliveriesRequest.query) &&
        Objects.equals(this.filters, searchDeliveriesRequest.filters) &&
        Objects.equals(this.sort, searchDeliveriesRequest.sort) &&
        Objects.equals(this.pagination, searchDeliveriesRequest.pagination);
  }

  @Override
  public int hashCode() {
    return Objects.hash(query, filters, sort, pagination);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchDeliveriesRequest {\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `query` to the URL query string
    if (getQuery() != null) {
      joiner.add(String.format("%squery%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQuery()))));
    }

    // add `filters` to the URL query string
    if (getFilters() != null) {
      for (String _key : getFilters().keySet()) {
        joiner.add(String.format("%sfilters%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
            getFilters().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getFilters().get(_key)))));
      }
    }

    // add `sort` to the URL query string
    if (getSort() != null) {
      for (int i = 0; i < getSort().size(); i++) {
        if (getSort().get(i) != null) {
          joiner.add(getSort().get(i).toUrlQueryString(String.format("%ssort%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `pagination` to the URL query string
    if (getPagination() != null) {
      joiner.add(getPagination().toUrlQueryString(prefix + "pagination" + suffix));
    }

    return joiner.toString();
  }
}

