/*
 * Service API
 * This API exposes endpoints.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zipper.delivery.hub.sdk.ApiClient;
/**
 * Optional request body for sending a test webhook event
 */
@JsonPropertyOrder({
  TestWebhookRequest.JSON_PROPERTY_TEST_FIELD
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class TestWebhookRequest {
  public static final String JSON_PROPERTY_TEST_FIELD = "testField";
  @jakarta.annotation.Nullable
  private String testField;

  public TestWebhookRequest() { 
  }

  public TestWebhookRequest testField(@jakarta.annotation.Nullable String testField) {
    this.testField = testField;
    return this;
  }

  /**
   * Custom payload for the test event; if omitted, a default value is used
   * @return testField
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEST_FIELD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTestField() {
    return testField;
  }


  @JsonProperty(JSON_PROPERTY_TEST_FIELD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTestField(@jakarta.annotation.Nullable String testField) {
    this.testField = testField;
  }


  /**
   * Return true if this TestWebhookRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestWebhookRequest testWebhookRequest = (TestWebhookRequest) o;
    return Objects.equals(this.testField, testWebhookRequest.testField);
  }

  @Override
  public int hashCode() {
    return Objects.hash(testField);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestWebhookRequest {\n");
    sb.append("    testField: ").append(toIndentedString(testField)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `testField` to the URL query string
    if (getTestField() != null) {
      joiner.add(String.format("%stestField%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTestField()))));
    }

    return joiner.toString();
  }
}

