/*
 * Service API
 * This API exposes endpoints.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zipper.delivery.hub.sdk.model.CallbackConfigDTO;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zipper.delivery.hub.sdk.ApiClient;
/**
 * Webhook subscription details
 */
@JsonPropertyOrder({
  WebhookDTO.JSON_PROPERTY_ID,
  WebhookDTO.JSON_PROPERTY_CALLBACK_URL,
  WebhookDTO.JSON_PROPERTY_ENABLED,
  WebhookDTO.JSON_PROPERTY_EVENT_TYPES,
  WebhookDTO.JSON_PROPERTY_CALLBACK_CONFIG,
  WebhookDTO.JSON_PROPERTY_CREATED_AT,
  WebhookDTO.JSON_PROPERTY_UPDATED_AT,
  WebhookDTO.JSON_PROPERTY_CLIENT_SECRET
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class WebhookDTO {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_CALLBACK_URL = "callbackUrl";
  @jakarta.annotation.Nullable
  private String callbackUrl;

  public static final String JSON_PROPERTY_ENABLED = "enabled";
  @jakarta.annotation.Nullable
  private Boolean enabled;

  public static final String JSON_PROPERTY_EVENT_TYPES = "eventTypes";
  @jakarta.annotation.Nullable
  private List<String> eventTypes = new ArrayList<>();

  public static final String JSON_PROPERTY_CALLBACK_CONFIG = "callbackConfig";
  @jakarta.annotation.Nullable
  private CallbackConfigDTO callbackConfig;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_CLIENT_SECRET = "clientSecret";
  @jakarta.annotation.Nullable
  private String clientSecret;

  public WebhookDTO() { 
  }

  public WebhookDTO id(@jakarta.annotation.Nullable Long id) {
    this.id = id;
    return this;
  }

  /**
   * Webhook ID
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }


  public WebhookDTO callbackUrl(@jakarta.annotation.Nullable String callbackUrl) {
    this.callbackUrl = callbackUrl;
    return this;
  }

  /**
   * Callback URL receiving events
   * @return callbackUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CALLBACK_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCallbackUrl() {
    return callbackUrl;
  }


  @JsonProperty(JSON_PROPERTY_CALLBACK_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCallbackUrl(@jakarta.annotation.Nullable String callbackUrl) {
    this.callbackUrl = callbackUrl;
  }


  public WebhookDTO enabled(@jakarta.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * Whether the webhook is active
   * @return enabled
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getEnabled() {
    return enabled;
  }


  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnabled(@jakarta.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
  }


  public WebhookDTO eventTypes(@jakarta.annotation.Nullable List<String> eventTypes) {
    this.eventTypes = eventTypes;
    return this;
  }

  public WebhookDTO addEventTypesItem(String eventTypesItem) {
    if (this.eventTypes == null) {
      this.eventTypes = new ArrayList<>();
    }
    this.eventTypes.add(eventTypesItem);
    return this;
  }

  /**
   * Subscribed event types
   * @return eventTypes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENT_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getEventTypes() {
    return eventTypes;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventTypes(@jakarta.annotation.Nullable List<String> eventTypes) {
    this.eventTypes = eventTypes;
  }


  public WebhookDTO callbackConfig(@jakarta.annotation.Nullable CallbackConfigDTO callbackConfig) {
    this.callbackConfig = callbackConfig;
    return this;
  }

  /**
   * Callback configuration (retry policy)
   * @return callbackConfig
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CALLBACK_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CallbackConfigDTO getCallbackConfig() {
    return callbackConfig;
  }


  @JsonProperty(JSON_PROPERTY_CALLBACK_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCallbackConfig(@jakarta.annotation.Nullable CallbackConfigDTO callbackConfig) {
    this.callbackConfig = callbackConfig;
  }


  public WebhookDTO createdAt(@jakarta.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Creation timestamp
   * @return createdAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@jakarta.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public WebhookDTO updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Last update timestamp
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public WebhookDTO clientSecret(@jakarta.annotation.Nullable String clientSecret) {
    this.clientSecret = clientSecret;
    return this;
  }

  /**
   * HMAC secret for verifying webhook signatures (only returned on creation)
   * @return clientSecret
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLIENT_SECRET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getClientSecret() {
    return clientSecret;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_SECRET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientSecret(@jakarta.annotation.Nullable String clientSecret) {
    this.clientSecret = clientSecret;
  }


  /**
   * Return true if this WebhookDTO object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookDTO webhookDTO = (WebhookDTO) o;
    return Objects.equals(this.id, webhookDTO.id) &&
        Objects.equals(this.callbackUrl, webhookDTO.callbackUrl) &&
        Objects.equals(this.enabled, webhookDTO.enabled) &&
        Objects.equals(this.eventTypes, webhookDTO.eventTypes) &&
        Objects.equals(this.callbackConfig, webhookDTO.callbackConfig) &&
        Objects.equals(this.createdAt, webhookDTO.createdAt) &&
        Objects.equals(this.updatedAt, webhookDTO.updatedAt) &&
        Objects.equals(this.clientSecret, webhookDTO.clientSecret);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, callbackUrl, enabled, eventTypes, callbackConfig, createdAt, updatedAt, clientSecret);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    callbackUrl: ").append(toIndentedString(callbackUrl)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    eventTypes: ").append(toIndentedString(eventTypes)).append("\n");
    sb.append("    callbackConfig: ").append(toIndentedString(callbackConfig)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    clientSecret: ").append(toIndentedString(clientSecret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format("%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `callbackUrl` to the URL query string
    if (getCallbackUrl() != null) {
      joiner.add(String.format("%scallbackUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCallbackUrl()))));
    }

    // add `enabled` to the URL query string
    if (getEnabled() != null) {
      joiner.add(String.format("%senabled%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEnabled()))));
    }

    // add `eventTypes` to the URL query string
    if (getEventTypes() != null) {
      for (int i = 0; i < getEventTypes().size(); i++) {
        joiner.add(String.format("%seventTypes%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getEventTypes().get(i)))));
      }
    }

    // add `callbackConfig` to the URL query string
    if (getCallbackConfig() != null) {
      joiner.add(getCallbackConfig().toUrlQueryString(prefix + "callbackConfig" + suffix));
    }

    // add `createdAt` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format("%screatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `updatedAt` to the URL query string
    if (getUpdatedAt() != null) {
      joiner.add(String.format("%supdatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUpdatedAt()))));
    }

    // add `clientSecret` to the URL query string
    if (getClientSecret() != null) {
      joiner.add(String.format("%sclientSecret%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getClientSecret()))));
    }

    return joiner.toString();
  }
}

