/*
 * Service API
 * This API exposes endpoints.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.zipper.delivery.hub.sdk.api;

import com.zipper.delivery.hub.sdk.ApiClient;
import com.zipper.delivery.hub.sdk.ApiException;
import com.zipper.delivery.hub.sdk.ApiResponse;
import com.zipper.delivery.hub.sdk.Configuration;
import com.zipper.delivery.hub.sdk.Pair;

import java.io.File;
import com.zipper.delivery.hub.sdk.model.HubCancelDeliveryResponse;
import com.zipper.delivery.hub.sdk.model.HubCreateDeliveryRequest;
import com.zipper.delivery.hub.sdk.model.HubCreateDeliveryResponse;
import com.zipper.delivery.hub.sdk.model.HubDeliveryLabelResponse;
import com.zipper.delivery.hub.sdk.model.HubDeliveryQuoteRequest;
import com.zipper.delivery.hub.sdk.model.HubDeliveryQuoteResponse;
import com.zipper.delivery.hub.sdk.model.HubDeliveryStatusResponse;
import com.zipper.delivery.hub.sdk.model.HubHandshakeDeliveryResponse;
import com.zipper.delivery.hub.sdk.model.PageResponseListHubDeliverySearchDTO;
import com.zipper.delivery.hub.sdk.model.SearchDeliveriesRequest;
import java.util.UUID;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class DeliveriesApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public DeliveriesApi() {
    this(Configuration.getDefaultApiClient());
  }

  public DeliveriesApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Cancel a delivery
   * Cancels a delivery that is in CREATED or ASSIGNED status. If the delivery has been dispatched to a provider, the cancellation is also forwarded to the provider.
   * @param deliveryId UUID of the delivery to cancel (required)
   * @return HubCancelDeliveryResponse
   * @throws ApiException if fails to make API call
   */
  public HubCancelDeliveryResponse cancelDelivery(@jakarta.annotation.Nonnull UUID deliveryId) throws ApiException {
    ApiResponse<HubCancelDeliveryResponse> localVarResponse = cancelDeliveryWithHttpInfo(deliveryId);
    return localVarResponse.getData();
  }

  /**
   * Cancel a delivery
   * Cancels a delivery that is in CREATED or ASSIGNED status. If the delivery has been dispatched to a provider, the cancellation is also forwarded to the provider.
   * @param deliveryId UUID of the delivery to cancel (required)
   * @return ApiResponse&lt;HubCancelDeliveryResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<HubCancelDeliveryResponse> cancelDeliveryWithHttpInfo(@jakarta.annotation.Nonnull UUID deliveryId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = cancelDeliveryRequestBuilder(deliveryId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("cancelDelivery", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<HubCancelDeliveryResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<HubCancelDeliveryResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<HubCancelDeliveryResponse>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder cancelDeliveryRequestBuilder(@jakarta.annotation.Nonnull UUID deliveryId) throws ApiException {
    // verify the required parameter 'deliveryId' is set
    if (deliveryId == null) {
      throw new ApiException(400, "Missing the required parameter 'deliveryId' when calling cancelDelivery");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/deliveries/{deliveryId}/cancel"
        .replace("{deliveryId}", ApiClient.urlEncode(deliveryId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Create a delivery
   * Dispatches a new delivery order to the best available carrier provider. An optional idempotency key prevents duplicate orders.
   * @param hubCreateDeliveryRequest  (required)
   * @param idempotencyKey Unique key to ensure idempotent delivery creation (optional)
   * @return HubCreateDeliveryResponse
   * @throws ApiException if fails to make API call
   */
  public HubCreateDeliveryResponse createDelivery(@jakarta.annotation.Nonnull HubCreateDeliveryRequest hubCreateDeliveryRequest, @jakarta.annotation.Nullable String idempotencyKey) throws ApiException {
    ApiResponse<HubCreateDeliveryResponse> localVarResponse = createDeliveryWithHttpInfo(hubCreateDeliveryRequest, idempotencyKey);
    return localVarResponse.getData();
  }

  /**
   * Create a delivery
   * Dispatches a new delivery order to the best available carrier provider. An optional idempotency key prevents duplicate orders.
   * @param hubCreateDeliveryRequest  (required)
   * @param idempotencyKey Unique key to ensure idempotent delivery creation (optional)
   * @return ApiResponse&lt;HubCreateDeliveryResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<HubCreateDeliveryResponse> createDeliveryWithHttpInfo(@jakarta.annotation.Nonnull HubCreateDeliveryRequest hubCreateDeliveryRequest, @jakarta.annotation.Nullable String idempotencyKey) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createDeliveryRequestBuilder(hubCreateDeliveryRequest, idempotencyKey);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createDelivery", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<HubCreateDeliveryResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<HubCreateDeliveryResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<HubCreateDeliveryResponse>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createDeliveryRequestBuilder(@jakarta.annotation.Nonnull HubCreateDeliveryRequest hubCreateDeliveryRequest, @jakarta.annotation.Nullable String idempotencyKey) throws ApiException {
    // verify the required parameter 'hubCreateDeliveryRequest' is set
    if (hubCreateDeliveryRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'hubCreateDeliveryRequest' when calling createDelivery");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/deliveries";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (idempotencyKey != null) {
      localVarRequestBuilder.header("Idempotency-Key", idempotencyKey.toString());
    }
    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "*/*");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(hubCreateDeliveryRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get delivery status
   * Retrieves the current status, tracking information, and full status history of a delivery.
   * @param deliveryId UUID of the delivery to retrieve (required)
   * @return HubDeliveryStatusResponse
   * @throws ApiException if fails to make API call
   */
  public HubDeliveryStatusResponse getDelivery(@jakarta.annotation.Nonnull UUID deliveryId) throws ApiException {
    ApiResponse<HubDeliveryStatusResponse> localVarResponse = getDeliveryWithHttpInfo(deliveryId);
    return localVarResponse.getData();
  }

  /**
   * Get delivery status
   * Retrieves the current status, tracking information, and full status history of a delivery.
   * @param deliveryId UUID of the delivery to retrieve (required)
   * @return ApiResponse&lt;HubDeliveryStatusResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<HubDeliveryStatusResponse> getDeliveryWithHttpInfo(@jakarta.annotation.Nonnull UUID deliveryId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getDeliveryRequestBuilder(deliveryId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getDelivery", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<HubDeliveryStatusResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<HubDeliveryStatusResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<HubDeliveryStatusResponse>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getDeliveryRequestBuilder(@jakarta.annotation.Nonnull UUID deliveryId) throws ApiException {
    // verify the required parameter 'deliveryId' is set
    if (deliveryId == null) {
      throw new ApiException(400, "Missing the required parameter 'deliveryId' when calling getDelivery");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/deliveries/{deliveryId}"
        .replace("{deliveryId}", ApiClient.urlEncode(deliveryId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get delivery label metadata
   * Returns barcode value and URLs for barcode image, QR code, and label PDF for a delivery identified by its hub tracking number.
   * @param hubTrackingNumber Hub tracking number (required)
   * @return HubDeliveryLabelResponse
   * @throws ApiException if fails to make API call
   */
  public HubDeliveryLabelResponse getDeliveryLabel(@jakarta.annotation.Nonnull String hubTrackingNumber) throws ApiException {
    ApiResponse<HubDeliveryLabelResponse> localVarResponse = getDeliveryLabelWithHttpInfo(hubTrackingNumber);
    return localVarResponse.getData();
  }

  /**
   * Get delivery label metadata
   * Returns barcode value and URLs for barcode image, QR code, and label PDF for a delivery identified by its hub tracking number.
   * @param hubTrackingNumber Hub tracking number (required)
   * @return ApiResponse&lt;HubDeliveryLabelResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<HubDeliveryLabelResponse> getDeliveryLabelWithHttpInfo(@jakarta.annotation.Nonnull String hubTrackingNumber) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getDeliveryLabelRequestBuilder(hubTrackingNumber);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getDeliveryLabel", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<HubDeliveryLabelResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<HubDeliveryLabelResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<HubDeliveryLabelResponse>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getDeliveryLabelRequestBuilder(@jakarta.annotation.Nonnull String hubTrackingNumber) throws ApiException {
    // verify the required parameter 'hubTrackingNumber' is set
    if (hubTrackingNumber == null) {
      throw new ApiException(400, "Missing the required parameter 'hubTrackingNumber' when calling getDeliveryLabel");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/deliveries/{hubTrackingNumber}/label"
        .replace("{hubTrackingNumber}", ApiClient.urlEncode(hubTrackingNumber.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Download a label asset
   * Serves a label asset (barcode.png, qrcode.png, or label.pdf) for a delivery. Streams from storage or generates on-the-fly if not yet uploaded.
   * @param hubTrackingNumber Hub tracking number (required)
   * @param filename Asset filename (required)
   * @return File
   * @throws ApiException if fails to make API call
   */
  public File getDeliveryLabelAsset(@jakarta.annotation.Nonnull String hubTrackingNumber, @jakarta.annotation.Nonnull String filename) throws ApiException {
    ApiResponse<File> localVarResponse = getDeliveryLabelAssetWithHttpInfo(hubTrackingNumber, filename);
    return localVarResponse.getData();
  }

  /**
   * Download a label asset
   * Serves a label asset (barcode.png, qrcode.png, or label.pdf) for a delivery. Streams from storage or generates on-the-fly if not yet uploaded.
   * @param hubTrackingNumber Hub tracking number (required)
   * @param filename Asset filename (required)
   * @return ApiResponse&lt;File&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<File> getDeliveryLabelAssetWithHttpInfo(@jakarta.annotation.Nonnull String hubTrackingNumber, @jakarta.annotation.Nonnull String filename) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getDeliveryLabelAssetRequestBuilder(hubTrackingNumber, filename);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getDeliveryLabelAsset", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<File>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<File>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<File>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getDeliveryLabelAssetRequestBuilder(@jakarta.annotation.Nonnull String hubTrackingNumber, @jakarta.annotation.Nonnull String filename) throws ApiException {
    // verify the required parameter 'hubTrackingNumber' is set
    if (hubTrackingNumber == null) {
      throw new ApiException(400, "Missing the required parameter 'hubTrackingNumber' when calling getDeliveryLabelAsset");
    }
    // verify the required parameter 'filename' is set
    if (filename == null) {
      throw new ApiException(400, "Missing the required parameter 'filename' when calling getDeliveryLabelAsset");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/deliveries/{hubTrackingNumber}/label/{filename}"
        .replace("{hubTrackingNumber}", ApiClient.urlEncode(hubTrackingNumber.toString()))
        .replace("{filename}", ApiClient.urlEncode(filename.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get handshake PIN info
   * Returns PIN handshake information for a delivery, including whether a PIN is required and the PIN code if applicable.
   * @param deliveryId UUID of the delivery (required)
   * @return HubHandshakeDeliveryResponse
   * @throws ApiException if fails to make API call
   */
  public HubHandshakeDeliveryResponse getHandshakeDelivery(@jakarta.annotation.Nonnull UUID deliveryId) throws ApiException {
    ApiResponse<HubHandshakeDeliveryResponse> localVarResponse = getHandshakeDeliveryWithHttpInfo(deliveryId);
    return localVarResponse.getData();
  }

  /**
   * Get handshake PIN info
   * Returns PIN handshake information for a delivery, including whether a PIN is required and the PIN code if applicable.
   * @param deliveryId UUID of the delivery (required)
   * @return ApiResponse&lt;HubHandshakeDeliveryResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<HubHandshakeDeliveryResponse> getHandshakeDeliveryWithHttpInfo(@jakarta.annotation.Nonnull UUID deliveryId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getHandshakeDeliveryRequestBuilder(deliveryId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getHandshakeDelivery", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<HubHandshakeDeliveryResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<HubHandshakeDeliveryResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<HubHandshakeDeliveryResponse>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getHandshakeDeliveryRequestBuilder(@jakarta.annotation.Nonnull UUID deliveryId) throws ApiException {
    // verify the required parameter 'deliveryId' is set
    if (deliveryId == null) {
      throw new ApiException(400, "Missing the required parameter 'deliveryId' when calling getHandshakeDelivery");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/deliveries/{deliveryId}/handshake"
        .replace("{deliveryId}", ApiClient.urlEncode(deliveryId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get a delivery quote
   * Returns a price quote and estimated arrival time for the given pickup/dropoff route and delivery type.
   * @param hubDeliveryQuoteRequest  (required)
   * @return HubDeliveryQuoteResponse
   * @throws ApiException if fails to make API call
   */
  public HubDeliveryQuoteResponse getQuote(@jakarta.annotation.Nonnull HubDeliveryQuoteRequest hubDeliveryQuoteRequest) throws ApiException {
    ApiResponse<HubDeliveryQuoteResponse> localVarResponse = getQuoteWithHttpInfo(hubDeliveryQuoteRequest);
    return localVarResponse.getData();
  }

  /**
   * Get a delivery quote
   * Returns a price quote and estimated arrival time for the given pickup/dropoff route and delivery type.
   * @param hubDeliveryQuoteRequest  (required)
   * @return ApiResponse&lt;HubDeliveryQuoteResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<HubDeliveryQuoteResponse> getQuoteWithHttpInfo(@jakarta.annotation.Nonnull HubDeliveryQuoteRequest hubDeliveryQuoteRequest) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getQuoteRequestBuilder(hubDeliveryQuoteRequest);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getQuote", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<HubDeliveryQuoteResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<HubDeliveryQuoteResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<HubDeliveryQuoteResponse>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getQuoteRequestBuilder(@jakarta.annotation.Nonnull HubDeliveryQuoteRequest hubDeliveryQuoteRequest) throws ApiException {
    // verify the required parameter 'hubDeliveryQuoteRequest' is set
    if (hubDeliveryQuoteRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'hubDeliveryQuoteRequest' when calling getQuote");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/deliveries/quote";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "*/*");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(hubDeliveryQuoteRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Search deliveries
   * Search and filter deliveries with pagination. Supports filtering by status, date range, and other criteria. Returns a paginated list of deliveries matching the search parameters.
   * @param searchDeliveriesRequest  (required)
   * @return PageResponseListHubDeliverySearchDTO
   * @throws ApiException if fails to make API call
   */
  public PageResponseListHubDeliverySearchDTO searchDeliveries(@jakarta.annotation.Nonnull SearchDeliveriesRequest searchDeliveriesRequest) throws ApiException {
    ApiResponse<PageResponseListHubDeliverySearchDTO> localVarResponse = searchDeliveriesWithHttpInfo(searchDeliveriesRequest);
    return localVarResponse.getData();
  }

  /**
   * Search deliveries
   * Search and filter deliveries with pagination. Supports filtering by status, date range, and other criteria. Returns a paginated list of deliveries matching the search parameters.
   * @param searchDeliveriesRequest  (required)
   * @return ApiResponse&lt;PageResponseListHubDeliverySearchDTO&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PageResponseListHubDeliverySearchDTO> searchDeliveriesWithHttpInfo(@jakarta.annotation.Nonnull SearchDeliveriesRequest searchDeliveriesRequest) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = searchDeliveriesRequestBuilder(searchDeliveriesRequest);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("searchDeliveries", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<PageResponseListHubDeliverySearchDTO>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<PageResponseListHubDeliverySearchDTO>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<PageResponseListHubDeliverySearchDTO>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder searchDeliveriesRequestBuilder(@jakarta.annotation.Nonnull SearchDeliveriesRequest searchDeliveriesRequest) throws ApiException {
    // verify the required parameter 'searchDeliveriesRequest' is set
    if (searchDeliveriesRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'searchDeliveriesRequest' when calling searchDeliveries");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/deliveries/search";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "*/*");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(searchDeliveriesRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Track delivery by tracking number
   * Retrieves delivery status and tracking information using the hub tracking number. This endpoint is designed for easy tracking URL sharing and does not require authentication, but will only return information for deliveries that have been marked as &#39;trackable&#39; by the sender.
   * @param hubTrackingNumber Hub tracking number (required)
   * @return HubDeliveryStatusResponse
   * @throws ApiException if fails to make API call
   */
  public HubDeliveryStatusResponse trackDelivery(@jakarta.annotation.Nonnull String hubTrackingNumber) throws ApiException {
    ApiResponse<HubDeliveryStatusResponse> localVarResponse = trackDeliveryWithHttpInfo(hubTrackingNumber);
    return localVarResponse.getData();
  }

  /**
   * Track delivery by tracking number
   * Retrieves delivery status and tracking information using the hub tracking number. This endpoint is designed for easy tracking URL sharing and does not require authentication, but will only return information for deliveries that have been marked as &#39;trackable&#39; by the sender.
   * @param hubTrackingNumber Hub tracking number (required)
   * @return ApiResponse&lt;HubDeliveryStatusResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<HubDeliveryStatusResponse> trackDeliveryWithHttpInfo(@jakarta.annotation.Nonnull String hubTrackingNumber) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = trackDeliveryRequestBuilder(hubTrackingNumber);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("trackDelivery", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<HubDeliveryStatusResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<HubDeliveryStatusResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<HubDeliveryStatusResponse>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder trackDeliveryRequestBuilder(@jakarta.annotation.Nonnull String hubTrackingNumber) throws ApiException {
    // verify the required parameter 'hubTrackingNumber' is set
    if (hubTrackingNumber == null) {
      throw new ApiException(400, "Missing the required parameter 'hubTrackingNumber' when calling trackDelivery");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/deliveries/track/{hubTrackingNumber}"
        .replace("{hubTrackingNumber}", ApiClient.urlEncode(hubTrackingNumber.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
