/*
 * Service API
 * This API exposes endpoints.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.api;

import com.zipper.delivery.hub.sdk.ApiCallback;
import com.zipper.delivery.hub.sdk.ApiClient;
import com.zipper.delivery.hub.sdk.ApiException;
import com.zipper.delivery.hub.sdk.ApiResponse;
import com.zipper.delivery.hub.sdk.Configuration;
import com.zipper.delivery.hub.sdk.Pair;
import com.zipper.delivery.hub.sdk.ProgressRequestBody;
import com.zipper.delivery.hub.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.zipper.delivery.hub.sdk.model.OAuth2ErrorResponse;
import com.zipper.delivery.hub.sdk.model.OAuth2TokenResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class OAuth2Api {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public OAuth2Api() {
        this(Configuration.getDefaultApiClient());
    }

    public OAuth2Api(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for token
     * @param grantType OAuth2 grant type (must be &#39;client_credentials&#39;) (required)
     * @param clientId API client identifier (required)
     * @param clientSecret API client secret key (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Access token issued successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Unsupported grant type </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Invalid client credentials or inactive account </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call tokenCall(@javax.annotation.Nonnull String grantType, @javax.annotation.Nonnull String clientId, @javax.annotation.Nonnull String clientSecret, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/auth/oauth/token";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (grantType != null) {
            localVarFormParams.put("grant_type", grantType);
        }

        if (clientId != null) {
            localVarFormParams.put("client_id", clientId);
        }

        if (clientSecret != null) {
            localVarFormParams.put("client_secret", clientSecret);
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (acceptLanguage != null) {
            localVarHeaderParams.put("Accept-Language", localVarApiClient.parameterToString(acceptLanguage));
        }


        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call tokenValidateBeforeCall(@javax.annotation.Nonnull String grantType, @javax.annotation.Nonnull String clientId, @javax.annotation.Nonnull String clientSecret, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'grantType' is set
        if (grantType == null) {
            throw new ApiException("Missing the required parameter 'grantType' when calling token(Async)");
        }

        // verify the required parameter 'clientId' is set
        if (clientId == null) {
            throw new ApiException("Missing the required parameter 'clientId' when calling token(Async)");
        }

        // verify the required parameter 'clientSecret' is set
        if (clientSecret == null) {
            throw new ApiException("Missing the required parameter 'clientSecret' when calling token(Async)");
        }

        return tokenCall(grantType, clientId, clientSecret, acceptLanguage, _callback);

    }

    /**
     * Exchange client credentials for an access token
     * Issues a JWT access token in exchange for valid API client credentials using the client_credentials grant type.
     * @param grantType OAuth2 grant type (must be &#39;client_credentials&#39;) (required)
     * @param clientId API client identifier (required)
     * @param clientSecret API client secret key (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return OAuth2TokenResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Access token issued successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Unsupported grant type </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Invalid client credentials or inactive account </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public OAuth2TokenResponse token(@javax.annotation.Nonnull String grantType, @javax.annotation.Nonnull String clientId, @javax.annotation.Nonnull String clientSecret, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        ApiResponse<OAuth2TokenResponse> localVarResp = tokenWithHttpInfo(grantType, clientId, clientSecret, acceptLanguage);
        return localVarResp.getData();
    }

    /**
     * Exchange client credentials for an access token
     * Issues a JWT access token in exchange for valid API client credentials using the client_credentials grant type.
     * @param grantType OAuth2 grant type (must be &#39;client_credentials&#39;) (required)
     * @param clientId API client identifier (required)
     * @param clientSecret API client secret key (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return ApiResponse&lt;OAuth2TokenResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Access token issued successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Unsupported grant type </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Invalid client credentials or inactive account </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<OAuth2TokenResponse> tokenWithHttpInfo(@javax.annotation.Nonnull String grantType, @javax.annotation.Nonnull String clientId, @javax.annotation.Nonnull String clientSecret, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        okhttp3.Call localVarCall = tokenValidateBeforeCall(grantType, clientId, clientSecret, acceptLanguage, null);
        Type localVarReturnType = new TypeToken<OAuth2TokenResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Exchange client credentials for an access token (asynchronously)
     * Issues a JWT access token in exchange for valid API client credentials using the client_credentials grant type.
     * @param grantType OAuth2 grant type (must be &#39;client_credentials&#39;) (required)
     * @param clientId API client identifier (required)
     * @param clientSecret API client secret key (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Access token issued successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Unsupported grant type </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Invalid client credentials or inactive account </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call tokenAsync(@javax.annotation.Nonnull String grantType, @javax.annotation.Nonnull String clientId, @javax.annotation.Nonnull String clientSecret, @javax.annotation.Nullable String acceptLanguage, final ApiCallback<OAuth2TokenResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = tokenValidateBeforeCall(grantType, clientId, clientSecret, acceptLanguage, _callback);
        Type localVarReturnType = new TypeToken<OAuth2TokenResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
