/*
 * Service API
 * This API exposes endpoints.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.delivery.hub.sdk.api;

import com.zipper.delivery.hub.sdk.ApiCallback;
import com.zipper.delivery.hub.sdk.ApiClient;
import com.zipper.delivery.hub.sdk.ApiException;
import com.zipper.delivery.hub.sdk.ApiResponse;
import com.zipper.delivery.hub.sdk.Configuration;
import com.zipper.delivery.hub.sdk.Pair;
import com.zipper.delivery.hub.sdk.ProgressRequestBody;
import com.zipper.delivery.hub.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.zipper.delivery.hub.sdk.model.CreateWebhookRequest;
import com.zipper.delivery.hub.sdk.model.TestWebhookRequest;
import com.zipper.delivery.hub.sdk.model.UpdateWebhookRequest;
import com.zipper.delivery.hub.sdk.model.WebhookDTO;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class WebhooksApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public WebhooksApi() {
        this(Configuration.getDefaultApiClient());
    }

    public WebhooksApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createWebhook
     * @param createWebhookRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Webhook created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden — insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Webhook with this callback URL already exists </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createWebhookCall(@javax.annotation.Nonnull CreateWebhookRequest createWebhookRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createWebhookRequest;

        // create path and map variables
        String localVarPath = "/api/v1/webhooks";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createWebhookValidateBeforeCall(@javax.annotation.Nonnull CreateWebhookRequest createWebhookRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'createWebhookRequest' is set
        if (createWebhookRequest == null) {
            throw new ApiException("Missing the required parameter 'createWebhookRequest' when calling createWebhook(Async)");
        }

        return createWebhookCall(createWebhookRequest, _callback);

    }

    /**
     * Create a webhook
     * Registers a new webhook for the current API client. Returns 409 Conflict if a webhook with the same callback URL already exists.
     * @param createWebhookRequest  (required)
     * @return WebhookDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Webhook created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden — insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Webhook with this callback URL already exists </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public WebhookDTO createWebhook(@javax.annotation.Nonnull CreateWebhookRequest createWebhookRequest) throws ApiException {
        ApiResponse<WebhookDTO> localVarResp = createWebhookWithHttpInfo(createWebhookRequest);
        return localVarResp.getData();
    }

    /**
     * Create a webhook
     * Registers a new webhook for the current API client. Returns 409 Conflict if a webhook with the same callback URL already exists.
     * @param createWebhookRequest  (required)
     * @return ApiResponse&lt;WebhookDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Webhook created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden — insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Webhook with this callback URL already exists </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<WebhookDTO> createWebhookWithHttpInfo(@javax.annotation.Nonnull CreateWebhookRequest createWebhookRequest) throws ApiException {
        okhttp3.Call localVarCall = createWebhookValidateBeforeCall(createWebhookRequest, null);
        Type localVarReturnType = new TypeToken<WebhookDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create a webhook (asynchronously)
     * Registers a new webhook for the current API client. Returns 409 Conflict if a webhook with the same callback URL already exists.
     * @param createWebhookRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Webhook created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden — insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Webhook with this callback URL already exists </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createWebhookAsync(@javax.annotation.Nonnull CreateWebhookRequest createWebhookRequest, final ApiCallback<WebhookDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = createWebhookValidateBeforeCall(createWebhookRequest, _callback);
        Type localVarReturnType = new TypeToken<WebhookDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteWebhookById
     * @param id Webhook ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Webhook deleted </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden — insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Webhook not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteWebhookByIdCall(@javax.annotation.Nonnull Long id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/webhooks/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteWebhookByIdValidateBeforeCall(@javax.annotation.Nonnull Long id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling deleteWebhookById(Async)");
        }

        return deleteWebhookByIdCall(id, _callback);

    }

    /**
     * Delete a specific webhook
     * Removes a specific webhook subscription by ID for the current API client.
     * @param id Webhook ID (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Webhook deleted </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden — insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Webhook not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public void deleteWebhookById(@javax.annotation.Nonnull Long id) throws ApiException {
        deleteWebhookByIdWithHttpInfo(id);
    }

    /**
     * Delete a specific webhook
     * Removes a specific webhook subscription by ID for the current API client.
     * @param id Webhook ID (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Webhook deleted </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden — insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Webhook not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> deleteWebhookByIdWithHttpInfo(@javax.annotation.Nonnull Long id) throws ApiException {
        okhttp3.Call localVarCall = deleteWebhookByIdValidateBeforeCall(id, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Delete a specific webhook (asynchronously)
     * Removes a specific webhook subscription by ID for the current API client.
     * @param id Webhook ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Webhook deleted </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden — insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Webhook not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteWebhookByIdAsync(@javax.annotation.Nonnull Long id, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteWebhookByIdValidateBeforeCall(id, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for listWebhooks
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of webhooks </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden — insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listWebhooksCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/webhooks";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listWebhooksValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return listWebhooksCall(_callback);

    }

    /**
     * List all webhooks
     * Returns all webhook subscriptions for the current API client.
     * @return List&lt;WebhookDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of webhooks </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden — insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public List<WebhookDTO> listWebhooks() throws ApiException {
        ApiResponse<List<WebhookDTO>> localVarResp = listWebhooksWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * List all webhooks
     * Returns all webhook subscriptions for the current API client.
     * @return ApiResponse&lt;List&lt;WebhookDTO&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of webhooks </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden — insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<WebhookDTO>> listWebhooksWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = listWebhooksValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<List<WebhookDTO>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List all webhooks (asynchronously)
     * Returns all webhook subscriptions for the current API client.
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of webhooks </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden — insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listWebhooksAsync(final ApiCallback<List<WebhookDTO>> _callback) throws ApiException {

        okhttp3.Call localVarCall = listWebhooksValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<List<WebhookDTO>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for testWebhook
     * @param testWebhookRequest  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Test event accepted for delivery </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden — insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No webhook registered for this client </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call testWebhookCall(@javax.annotation.Nullable TestWebhookRequest testWebhookRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = testWebhookRequest;

        // create path and map variables
        String localVarPath = "/api/v1/webhooks/test";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call testWebhookValidateBeforeCall(@javax.annotation.Nullable TestWebhookRequest testWebhookRequest, final ApiCallback _callback) throws ApiException {
        return testWebhookCall(testWebhookRequest, _callback);

    }

    /**
     * Send a test webhook event
     * Publishes a test event to all registered webhooks for the current API client.
     * @param testWebhookRequest  (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Test event accepted for delivery </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden — insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No webhook registered for this client </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public void testWebhook(@javax.annotation.Nullable TestWebhookRequest testWebhookRequest) throws ApiException {
        testWebhookWithHttpInfo(testWebhookRequest);
    }

    /**
     * Send a test webhook event
     * Publishes a test event to all registered webhooks for the current API client.
     * @param testWebhookRequest  (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Test event accepted for delivery </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden — insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No webhook registered for this client </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> testWebhookWithHttpInfo(@javax.annotation.Nullable TestWebhookRequest testWebhookRequest) throws ApiException {
        okhttp3.Call localVarCall = testWebhookValidateBeforeCall(testWebhookRequest, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Send a test webhook event (asynchronously)
     * Publishes a test event to all registered webhooks for the current API client.
     * @param testWebhookRequest  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Test event accepted for delivery </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden — insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No webhook registered for this client </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call testWebhookAsync(@javax.annotation.Nullable TestWebhookRequest testWebhookRequest, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = testWebhookValidateBeforeCall(testWebhookRequest, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateWebhook
     * @param id Webhook ID (required)
     * @param updateWebhookRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Webhook updated </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden — insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Webhook not found </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Webhook with this callback URL already exists </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateWebhookCall(@javax.annotation.Nonnull Long id, @javax.annotation.Nonnull UpdateWebhookRequest updateWebhookRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updateWebhookRequest;

        // create path and map variables
        String localVarPath = "/api/v1/webhooks/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateWebhookValidateBeforeCall(@javax.annotation.Nonnull Long id, @javax.annotation.Nonnull UpdateWebhookRequest updateWebhookRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling updateWebhook(Async)");
        }

        // verify the required parameter 'updateWebhookRequest' is set
        if (updateWebhookRequest == null) {
            throw new ApiException("Missing the required parameter 'updateWebhookRequest' when calling updateWebhook(Async)");
        }

        return updateWebhookCall(id, updateWebhookRequest, _callback);

    }

    /**
     * Update a webhook
     * Updates an existing webhook subscription by ID for the current API client.
     * @param id Webhook ID (required)
     * @param updateWebhookRequest  (required)
     * @return WebhookDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Webhook updated </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden — insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Webhook not found </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Webhook with this callback URL already exists </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public WebhookDTO updateWebhook(@javax.annotation.Nonnull Long id, @javax.annotation.Nonnull UpdateWebhookRequest updateWebhookRequest) throws ApiException {
        ApiResponse<WebhookDTO> localVarResp = updateWebhookWithHttpInfo(id, updateWebhookRequest);
        return localVarResp.getData();
    }

    /**
     * Update a webhook
     * Updates an existing webhook subscription by ID for the current API client.
     * @param id Webhook ID (required)
     * @param updateWebhookRequest  (required)
     * @return ApiResponse&lt;WebhookDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Webhook updated </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden — insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Webhook not found </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Webhook with this callback URL already exists </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<WebhookDTO> updateWebhookWithHttpInfo(@javax.annotation.Nonnull Long id, @javax.annotation.Nonnull UpdateWebhookRequest updateWebhookRequest) throws ApiException {
        okhttp3.Call localVarCall = updateWebhookValidateBeforeCall(id, updateWebhookRequest, null);
        Type localVarReturnType = new TypeToken<WebhookDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update a webhook (asynchronously)
     * Updates an existing webhook subscription by ID for the current API client.
     * @param id Webhook ID (required)
     * @param updateWebhookRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Webhook updated </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden — insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Webhook not found </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Webhook with this callback URL already exists </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateWebhookAsync(@javax.annotation.Nonnull Long id, @javax.annotation.Nonnull UpdateWebhookRequest updateWebhookRequest, final ApiCallback<WebhookDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateWebhookValidateBeforeCall(id, updateWebhookRequest, _callback);
        Type localVarReturnType = new TypeToken<WebhookDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
