/*
 * Service API
 * This API exposes endpoints.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.zipper.delivery.hub.sdk.api;

import com.zipper.delivery.hub.sdk.ApiClient;
import com.zipper.delivery.hub.sdk.ApiException;
import com.zipper.delivery.hub.sdk.ApiResponse;
import com.zipper.delivery.hub.sdk.Configuration;
import com.zipper.delivery.hub.sdk.Pair;

import com.zipper.delivery.hub.sdk.model.CreateWebhookRequest;
import com.zipper.delivery.hub.sdk.model.TestWebhookRequest;
import com.zipper.delivery.hub.sdk.model.UpdateWebhookRequest;
import com.zipper.delivery.hub.sdk.model.WebhookDTO;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import org.apache.http.HttpEntity;
import org.apache.http.NameValuePair;
import org.apache.http.entity.mime.MultipartEntityBuilder;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.client.entity.UrlEncodedFormEntity;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class WebhooksApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public WebhooksApi() {
    this(Configuration.getDefaultApiClient());
  }

  public WebhooksApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Create a webhook
   * Registers a new webhook for the current API client. Returns 409 Conflict if a webhook with the same callback URL already exists.
   * @param createWebhookRequest  (required)
   * @return WebhookDTO
   * @throws ApiException if fails to make API call
   */
  public WebhookDTO createWebhook(@jakarta.annotation.Nonnull CreateWebhookRequest createWebhookRequest) throws ApiException {
    ApiResponse<WebhookDTO> localVarResponse = createWebhookWithHttpInfo(createWebhookRequest);
    return localVarResponse.getData();
  }

  /**
   * Create a webhook
   * Registers a new webhook for the current API client. Returns 409 Conflict if a webhook with the same callback URL already exists.
   * @param createWebhookRequest  (required)
   * @return ApiResponse&lt;WebhookDTO&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<WebhookDTO> createWebhookWithHttpInfo(@jakarta.annotation.Nonnull CreateWebhookRequest createWebhookRequest) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createWebhookRequestBuilder(createWebhookRequest);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createWebhook", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<WebhookDTO>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<WebhookDTO>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<WebhookDTO>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createWebhookRequestBuilder(@jakarta.annotation.Nonnull CreateWebhookRequest createWebhookRequest) throws ApiException {
    // verify the required parameter 'createWebhookRequest' is set
    if (createWebhookRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'createWebhookRequest' when calling createWebhook");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/webhooks";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "*/*");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(createWebhookRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete a specific webhook
   * Removes a specific webhook subscription by ID for the current API client.
   * @param id Webhook ID (required)
   * @throws ApiException if fails to make API call
   */
  public void deleteWebhookById(@jakarta.annotation.Nonnull Long id) throws ApiException {
    deleteWebhookByIdWithHttpInfo(id);
  }

  /**
   * Delete a specific webhook
   * Removes a specific webhook subscription by ID for the current API client.
   * @param id Webhook ID (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteWebhookByIdWithHttpInfo(@jakarta.annotation.Nonnull Long id) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteWebhookByIdRequestBuilder(id);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteWebhookById", localVarResponse);
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
          // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteWebhookByIdRequestBuilder(@jakarta.annotation.Nonnull Long id) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling deleteWebhookById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/webhooks/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List all webhooks
   * Returns all webhook subscriptions for the current API client.
   * @return List&lt;WebhookDTO&gt;
   * @throws ApiException if fails to make API call
   */
  public List<WebhookDTO> listWebhooks() throws ApiException {
    ApiResponse<List<WebhookDTO>> localVarResponse = listWebhooksWithHttpInfo();
    return localVarResponse.getData();
  }

  /**
   * List all webhooks
   * Returns all webhook subscriptions for the current API client.
   * @return ApiResponse&lt;List&lt;WebhookDTO&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<WebhookDTO>> listWebhooksWithHttpInfo() throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listWebhooksRequestBuilder();
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listWebhooks", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<List<WebhookDTO>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<List<WebhookDTO>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<WebhookDTO>>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listWebhooksRequestBuilder() throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/webhooks";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Send a test webhook event
   * Publishes a test event to all registered webhooks for the current API client.
   * @param testWebhookRequest  (optional)
   * @throws ApiException if fails to make API call
   */
  public void testWebhook(@jakarta.annotation.Nullable TestWebhookRequest testWebhookRequest) throws ApiException {
    testWebhookWithHttpInfo(testWebhookRequest);
  }

  /**
   * Send a test webhook event
   * Publishes a test event to all registered webhooks for the current API client.
   * @param testWebhookRequest  (optional)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> testWebhookWithHttpInfo(@jakarta.annotation.Nullable TestWebhookRequest testWebhookRequest) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = testWebhookRequestBuilder(testWebhookRequest);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("testWebhook", localVarResponse);
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
          // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder testWebhookRequestBuilder(@jakarta.annotation.Nullable TestWebhookRequest testWebhookRequest) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/webhooks/test";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(testWebhookRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Update a webhook
   * Updates an existing webhook subscription by ID for the current API client.
   * @param id Webhook ID (required)
   * @param updateWebhookRequest  (required)
   * @return WebhookDTO
   * @throws ApiException if fails to make API call
   */
  public WebhookDTO updateWebhook(@jakarta.annotation.Nonnull Long id, @jakarta.annotation.Nonnull UpdateWebhookRequest updateWebhookRequest) throws ApiException {
    ApiResponse<WebhookDTO> localVarResponse = updateWebhookWithHttpInfo(id, updateWebhookRequest);
    return localVarResponse.getData();
  }

  /**
   * Update a webhook
   * Updates an existing webhook subscription by ID for the current API client.
   * @param id Webhook ID (required)
   * @param updateWebhookRequest  (required)
   * @return ApiResponse&lt;WebhookDTO&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<WebhookDTO> updateWebhookWithHttpInfo(@jakarta.annotation.Nonnull Long id, @jakarta.annotation.Nonnull UpdateWebhookRequest updateWebhookRequest) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = updateWebhookRequestBuilder(id, updateWebhookRequest);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("updateWebhook", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<WebhookDTO>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<WebhookDTO>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<WebhookDTO>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder updateWebhookRequestBuilder(@jakarta.annotation.Nonnull Long id, @jakarta.annotation.Nonnull UpdateWebhookRequest updateWebhookRequest) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling updateWebhook");
    }
    // verify the required parameter 'updateWebhookRequest' is set
    if (updateWebhookRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'updateWebhookRequest' when calling updateWebhook");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/webhooks/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "*/*");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(updateWebhookRequest);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
